/* ItZip platform site - built by build-footers.ps1 from parts\.
   Do not edit this file. Edit parts\*.js and run build-footers.ps1. */

/* ===== brand-itzip.js ===== */
// ItZip - platform site. Everything site-specific lives here; the core parts read it.
// NOTE: no apostrophes in comments anywhere in these files. The QShop save-time checker
// does not understand comments and treats one as an unclosed string, which then makes it
// report a stray closing bracket and refuse to save.
window.FIT_BRAND = {
  key:          'itzip',
  homeId:       null,           // TODO: grid id of the ItZip home page once the site exists
  tel:          '1668-1561',    // consult button target
  // QShop page holding the reservation form we fill in, plus the 현장명/대표번호 table.
  // Deliberately an unguessable path. It has to stay publicly readable: the form is
  // loaded in the visitor browser, so locking it to admins would break every booking.
  contactPath:  '/contactadmin',
  campaignPath: '/r2D7Q',       // campaign list page guarded against blank SPA renders
  // No auto logo. The real ItZip logo is placed in the QShop header by hand, so the footer
  // code must not inject one of its own. viewBox and the two widths stay because the header
  // colour logic samples the background where the logo sits - keep them matched to the
  // artwork actually placed there. To bring the injected logo back, add an svg field here
  // (and drop auto:false); see brand-fittalk.js for the shape of it.
  logo: {
    auto:       false,
    viewBox:    '0 0 200 100',  // logo box shape - width x height of the placed artwork
    widthPC:    72,
    widthMobile: 60
  }
};

/* ===== core-1-logo.js ===== */
(function () {
  var B = window.FIT_BRAND || {}, BL = B.logo || {};
  // A brand with no svg artwork (or auto:false) supplies its own logo through the site
  // builder, so nothing is injected here. The rest of this part still runs: it drives the
  // header menu colour and the banner dressing, which have nothing to do with the wordmark.
  var AUTO  = !!BL.svg && BL.auto !== false;
  var W_PC  = BL.widthPC || 132;
  var W_MO  = BL.widthMobile || 106;
  var VB    = BL.viewBox || '0 0 1365.75 345.11';
  var vbn   = VB.split(/\s+/);
  var RATIO = (parseFloat(vbn[3]) || 1) / (parseFloat(vbn[2]) || 1);   // height per unit width
  var logo = document.getElementById('fit-logo');
  if (AUTO && !logo) {
  logo = document.createElement('a');
  logo.id = 'fit-logo'; logo.href = BL.href || '/'; logo.setAttribute('aria-label', BL.label || 'home');
  logo.style.cssText = 'position:fixed;left:24px;top:24px;width:' + W_PC + 'px;z-index:2147482999;opacity:1;transition:color .3s ease;line-height:0;color:#1b1b1b';
  logo.innerHTML = '<svg viewBox="' + VB + '" fill="currentColor" xmlns="http://www.w3.org/2000/svg" style="display:block;width:100%;height:auto">'
    + (BL.svg || '')
    + '</svg>';
  (document.body || document.documentElement).appendChild(logo);
  }
  // Accent shape inside the wordmark, if the brand has one. It is restored to its own
  // colour only while the logo is dark; on dark backgrounds it goes white with the rest.
  var mark = (logo && BL.markClass) ? logo.querySelector('.' + BL.markClass) : null;
  var MARK_COLOR = BL.markColor || '#3700ff';
  // Where the logo sits. With no injected element this is only a probe rectangle: the
  // background is sampled at its centre to decide the header colour.
  var box = { left: 24, top: 24, width: W_PC, height: W_PC * RATIO };
  function placeLogo() {
    var vw = document.documentElement.clientWidth;
    var mob = vw <= 768;
    var w = mob ? W_MO : W_PC, top;
    if (mob) {
      var logoH = W_MO * RATIO;                           // rendered logo height at mobile width
      var hs = document.getElementById('headerSection');
      var hh = hs ? hs.getBoundingClientRect().height : 0;
      top = hh > logoH + 4 ? Math.round((hh - logoH) / 2) : 15;
    } else {
      top = 24;
    }
    box.left = mob ? 18 : Math.max(0, vw / 2 - 640);
    box.top = top; box.width = w; box.height = w * RATIO;
    if (!logo) return;
    logo.style.left = mob ? '18px' : 'max(0px, calc(50% - 640px))';
    logo.style.width = w + 'px';
    logo.style.top = top + 'px';
  }
  placeLogo();
  setInterval(placeLogo, 300);
  window.addEventListener('resize', function () { placeLogo(); scheduleColor(); });

  var LOGO_DARK = '#1b1b1b', LOGO_LIGHT = '#fff';
  var LP = String.fromCharCode(40), RP = String.fromCharCode(41);
  function bgLumAt(x, y) {
    var els = document.elementsFromPoint(x, y);
    for (var i = 0; i < els.length; i++) {
      var el = els[i];
      if (logo && (el === logo || logo.contains(el))) continue;
      if (el.tagName === 'IFRAME') { try { if (el.contentDocument && el.contentDocument.querySelector('.zh-hero')) return 20; } catch (e) {} }
      var c = getComputedStyle(el).backgroundColor;
      var i1 = c.indexOf(LP), i2 = c.indexOf(RP);
      if (i1 >= 0 && i2 > i1) {
        var pp = c.slice(i1 + 1, i2).split(',');
        var a = pp.length > 3 ? parseFloat(pp[3]) : 1;
        if (a > 0.2) return 0.299 * parseFloat(pp[0]) + 0.587 * parseFloat(pp[1]) + 0.114 * parseFloat(pp[2]);
      }
    }
    return 255; // nothing solid found -> assume bright -> dark logo
  }
  function updateLogoColor() {
    var r = logo ? logo.getBoundingClientRect() : box;
    var cx = r.left + r.width / 2, cy = r.top + r.height / 2;
    var dark = bgLumAt(cx, cy) > 140;
    if (logo) logo.style.color = dark ? LOGO_DARK : LOGO_LIGHT; // text: light bg -> black, dark/blue bg -> white
    if (mark) {
      var mc = dark ? MARK_COLOR : LOGO_LIGHT;                 // accent colour only when logo is dark; white otherwise
      mark.style.fill = mc;
      mark.style.stroke = 'none';
    }
    var hs = document.getElementById('headerSection');
    if (hs) {
      var hdrDark = dark;
      var ovEl = document.getElementById('fit-ov'), ovUp = false;
      if (ovEl) { try { var oc = getComputedStyle(ovEl); ovUp = oc.display !== 'none' && oc.visibility !== 'hidden' && parseFloat(oc.opacity) > 0.1; } catch (e) { ovUp = true; } }
      if (!ovUp) {
        var rx = document.documentElement.clientWidth - 120;
        hdrDark = bgLumAt(rx, cy) > 140;
      }
      hs.style.setProperty('--fit-hdr', hdrDark ? LOGO_DARK : LOGO_LIGHT); // QShop header menu text follows this
    }
  }
  var colorRaf = 0;
  function scheduleColor() { if (!colorRaf) colorRaf = requestAnimationFrame(function () { colorRaf = 0; updateLogoColor(); }); }
  window.addEventListener('scroll', scheduleColor, { passive: true });
  scheduleColor();

  function bnFrame() {
    var fr = document.getElementsByTagName('iframe');
    for (var i = 0; i < fr.length; i++) {
      try { if (fr[i].contentDocument && fr[i].contentDocument.querySelector('.zh-hero')) return fr[i]; } catch (e) {}
      var src = fr[i].getAttribute('src') || '';   // cross-origin: cannot read innards, detect by widget URL
      if (src.indexOf('intro-banner') >= 0 || src.indexOf('zigbang') >= 0) return fr[i];
    }
    return null;
  }
  function bnStrip(f) {
    var host = f;
    for (var k = 0; k < 8 && host && host.tagName !== 'BODY'; k++) {
      host.style.setProperty('padding-top', '0', 'important');
      host.style.setProperty('padding-bottom', '0', 'important');
      host.style.setProperty('margin-top', '0', 'important');
      host.style.setProperty('margin-bottom', '0', 'important');
      if (host !== f) host.style.setProperty('background-color', 'transparent', 'important');
      host = host.parentElement;
    }
    var g0 = document.querySelector('#main [data-type="grid"][data-index="0"]');
    if (g0) g0.style.setProperty('background-color', 'transparent', 'important');
  }
  // The banner page used to run a hero mode: transparent header floating over the dark
  // banner. It now keeps the plain white header every other page has, so all that is left
  // here is stripping the grid padding so the banner still sits flush under the header.
  function bnDress() {
    var f = bnFrame();
    scheduleColor();
    if (!f) return;
    bnStrip(f);   // every tick, so it self-heals against QShop re-rendering the grid
    scheduleColor();
  }
  setInterval(bnDress, 300);
  window.addEventListener('scroll', bnDress, { passive: true });
  bnDress();
  document.addEventListener('click', function () {
    scheduleColor();
    setTimeout(scheduleColor, 60);
    setTimeout(scheduleColor, 280);
  }, true);
})();

/* ===== core-2-scroll.js ===== */
(function () {
  var FIT_SMOOTH = true;
  var EASE = 0.12;
  if (!FIT_SMOOTH) return;
  var mm = window.matchMedia;
  if (mm && mm('(prefers-reduced-motion: reduce)').matches) return; // user asked the OS to reduce motion
  if (mm && mm('(pointer: coarse)').matches) return;                // touch / mobile: leave native scroll alone
  if (!window.requestAnimationFrame) return;
  var target = window.pageYOffset || 0, current = target, raf = 0, busy = false, lastSet = -1;
  function maxY() { return Math.max(0, (document.documentElement.scrollHeight || 0) - window.innerHeight); }
  function loop() {
    var d = target - current;
    if (Math.abs(d) < 0.5) { current = target; lastSet = Math.round(current); window.scrollTo(0, lastSet); raf = 0; busy = false; return; }
    current += d * EASE;
    lastSet = Math.round(current);
    window.scrollTo(0, lastSet);
    raf = window.requestAnimationFrame(loop);
  }
  // Walk up from the wheel target looking for a nested scroller (modal bodies, policy
  // boxes, code blocks) that can still move in the requested direction. If we find one,
  // let the browser handle it natively instead of hijacking the page scroll.
  function innerScroller(node, dy) {
    while (node && node.nodeType === 1 && node !== document.body && node !== document.documentElement) {
      var oy = window.getComputedStyle(node).overflowY;
      if ((oy === 'auto' || oy === 'scroll' || oy === 'overlay') && node.scrollHeight > node.clientHeight + 1) {
        if (dy < 0 ? node.scrollTop > 0 : node.scrollTop + node.clientHeight < node.scrollHeight - 1) return node;
      }
      node = node.parentNode;
    }
    return null;
  }
  window.addEventListener('wheel', function (e) {
    if (e.ctrlKey) return;                       // pinch-zoom: do not interfere
    if (innerScroller(e.target, e.deltaY)) return;
    e.preventDefault();
    var step = e.deltaY;
    if (e.deltaMode === 1) step *= 16;           // line units to approx pixels
    else if (e.deltaMode === 2) step *= window.innerHeight;
    target = Math.max(0, Math.min(maxY(), target + step));
    busy = true;
    if (!raf) raf = window.requestAnimationFrame(loop);
  }, { passive: false });
  window.addEventListener('scroll', function () {
    if (!busy) { target = current = window.pageYOffset; return; }
    if (lastSet >= 0 && Math.abs(window.pageYOffset - lastSet) > 2) {
      target = current = window.pageYOffset; busy = false;
      if (raf) { window.cancelAnimationFrame(raf); raf = 0; }
    }
  }, { passive: true });
  window.addEventListener('resize', function () { target = Math.min(target, maxY()); });
})();

/* ===== core-3-tidy.js ===== */
(function () {
  var fix = null;
  var pin = document.createElement('style');
  pin.textContent = 'body.fit-nothome #fit-logo{opacity:1 !important}'
    + 'body.fit-nothome #main::before{display:none !important}'
    + 'body.fit-nothome{background-color:#ffffff !important}'
    + 'body.fit-nothome #headerSection{background-color:#ffffff !important}'
    + 'body.fit-nothome #headerSection [data-type=button] span,body.fit-nothome #headerSection [data-type=button] p{color:#1b1b1b !important}'
    + 'body.fit-nothome #headerSection [data-type=pageMenu] a{color:#1b1b1b !important;-webkit-text-fill-color:#1b1b1b !important}'
    + '#headerSection [data-type=pageMenu] a,#headerSection [data-type=button] span,#headerSection [data-type=button] p{color:var(--fit-hdr,#1b1b1b) !important;-webkit-text-fill-color:var(--fit-hdr,#1b1b1b) !important}';
  (document.head || document.documentElement).appendChild(pin);
  function tidy() {
    var homeId = (window.FIT_BRAND || {}).homeId;   // null until the site has a home grid id
    var home = window.__FIT_FORCE || (homeId ? document.getElementById(homeId) : null);
    if (document.body) document.body.classList.toggle('fit-nothome', !home);
    var ov = document.getElementById('fit-ov');
    var lg = document.getElementById('fit-logo');
    if (lg && !home) lg.style.opacity = '1';
    if (!home) {
      var g0 = document.querySelector('#main [data-type="grid"][data-index="0"]');
      if (g0) g0.style.setProperty('background-color', 'transparent', 'important');
      // inner header block goes transparent so the white on #headerSection shows through
      var hg = document.querySelector('#headerSection [data-type="header"]');
      if (hg) hg.style.setProperty('background-color', 'transparent', 'important');
    }
    if (!home && ov) {
      ov.remove();
      var sc = document.getElementById('fit-scrim'); if (sc) sc.remove();
      if (!fix) {
        fix = document.createElement('style'); fix.id = 'fit-tidy';
        fix.textContent = '#main::before{display:none !important}body{background-color:#ffffff !important}';
        (document.head || document.documentElement).appendChild(fix);
      }
    } else if (home && fix) {
      fix.remove(); fix = null;
    }
  }
  setInterval(tidy, 200);
  window.addEventListener('popstate', tidy);
  window.addEventListener('hashchange', tidy);
  tidy();

  function fitOnNav() {
    var i = 0;
    (function step() {
      tidy();
      if (i < 6) window.dispatchEvent(new Event('resize'));
      if (++i < 24 && window.requestAnimationFrame) window.requestAnimationFrame(step);
    })();
  }
  if (!window.__FIT_NAV_HOOK) {
    window.__FIT_NAV_HOOK = 1;
    ['pushState', 'replaceState'].forEach(function (m) {
      var orig = history[m];
      if (typeof orig === 'function') {
        history[m] = function () { var r = orig.apply(this, arguments); fitOnNav(); return r; };
      }
    });
    window.addEventListener('popstate', fitOnNav);
  }
})();

/* ===== core-4-menu.js ===== */
(function () {
  if (document.getElementById('fit-menu-skin')) return;
  var s = document.createElement('style');
  s.id = 'fit-menu-skin';
  s.textContent =
      '.Style_iconSubMenu__jzGJz{background-color:rgba(12,12,16,0.975) !important;backdrop-filter:blur(8px) !important;-webkit-backdrop-filter:blur(8px) !important}'
    + '.Style_iconSubMenu__jzGJz .Style_subMenu__OMBxT{position:fixed !important;left:0 !important;right:0 !important;top:0 !important;bottom:0 !important;width:auto !important;max-width:none !important;height:auto !important;transform:none !important;-webkit-transform:none !important;background:transparent !important;box-shadow:none !important;display:flex !important;flex-direction:column !important;justify-content:center !important;align-items:center !important;padding:0 28px !important;gap:0 !important}'
    + '.Style_iconSubMenu__jzGJz .Style_subMenu__OMBxT a,.Style_iconSubMenu__jzGJz .Style_subMenu__OMBxT a *{font-size:30px !important;font-weight:700 !important;color:#ffffff !important;-webkit-text-fill-color:#ffffff !important;line-height:1.5 !important;letter-spacing:-0.5px !important;text-decoration:none !important;word-break:keep-all !important}'
    + '.Style_iconSubMenu__jzGJz .Style_subMenu__OMBxT a{display:inline-block !important;transition:opacity .2s ease !important}'
    + '.Style_iconSubMenu__jzGJz .Style_subMenu__OMBxT a:active{opacity:.6 !important}'
    + '.Style_iconSubMenu__jzGJz .Style_subMenu__OMBxT > div:not(.Style_close__j_eS2){width:100% !important;text-align:center !important;border-top:1px solid #ffffff14;padding:14px 0 !important}'
    + '.Style_iconSubMenu__jzGJz .Style_subMenu__OMBxT > div:not(.Style_close__j_eS2):nth-child(2){border-top:none}'
    + '.Style_iconSubMenu__jzGJz .Style_subMenu__OMBxT > div:not(.Style_close__j_eS2) > div{text-align:center !important;display:block !important;width:100% !important;padding:0 !important;margin:0 !important}'
    + '.Style_iconSubMenu__jzGJz .Style_subMenu__OMBxT > div > div:nth-child(2){margin:8px 0 0 !important}'
    + '.Style_iconSubMenu__jzGJz .Style_subMenu__OMBxT > div > div:nth-child(2) a{padding:9px 0 !important}'
    + '.Style_iconSubMenu__jzGJz .Style_subMenu__OMBxT > div > div:nth-child(2) a,.Style_iconSubMenu__jzGJz .Style_subMenu__OMBxT > div > div:nth-child(2) a *{font-size:16px !important;font-weight:500 !important;color:#9a9aa4 !important;-webkit-text-fill-color:#9a9aa4 !important;line-height:1.4 !important;letter-spacing:-0.2px !important}'
    + '.Style_iconSubMenu__jzGJz .Style_subMenu__OMBxT div:not(:has(*)){font-size:12px !important;font-weight:700 !important;color:#7a7a85 !important;-webkit-text-fill-color:#7a7a85 !important;letter-spacing:3px !important;margin-top:26px !important;text-transform:uppercase !important}'
    + '.Style_iconSubMenu__jzGJz .Style_close__j_eS2{position:fixed !important;top:20px !important;right:18px !important;left:auto !important;display:flex !important;align-items:center !important;justify-content:center !important;width:44px !important;height:44px !important}'
    + '.Style_iconSubMenu__jzGJz .Style_close__j_eS2 svg{width:28px !important;height:28px !important}'
    + '.Style_iconSubMenu__jzGJz .Style_close__j_eS2 svg path{stroke:#ffffff !important;fill:#ffffff !important}'
    + '@keyframes fitMenuIn{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:none}}'
    + '.Style_iconSubMenu__jzGJz .Style_subMenu__OMBxT > div{animation:fitMenuIn .5s cubic-bezier(.22,1,.36,1) both}';
  (document.head || document.documentElement).appendChild(s);

  function reactOnClick(el){
    for (var k in el){ if (k.indexOf('__reactProps') === 0 && el[k] && typeof el[k].onClick === 'function') return el[k].onClick; }
    return null;
  }
  function closeMenu(){
    var cl = document.querySelector('.Style_close__j_eS2');
    if (!cl) return;
    var els = [cl].concat([].slice.call(cl.querySelectorAll('*')));
    for (var i = 0; i < els.length; i++){
      var fn = reactOnClick(els[i]);
      if (fn){ try { fn({ preventDefault: function(){}, stopPropagation: function(){}, currentTarget: els[i], target: els[i] }); } catch (e) {} return; }
    }
    try { cl.click(); } catch (e) {}
  }
  document.addEventListener('click', function (e) {
    var panel = document.querySelector('.Style_subMenu__OMBxT');
    if (!panel) return;                                  // menu is not open
    var t = e.target;
    if (!t || !t.closest) return;
    if (t.closest('a') || t.closest('.Style_close__j_eS2')) return;   // let links and the X behave normally
    if (t.closest('.Style_iconSubMenu__jzGJz')) closeMenu();
  }, true);
  setInterval(function () {
    var cl = document.querySelector('.Style_close__j_eS2');
    var lg = document.getElementById('fit-logo');
    if (!cl || !lg) return;
    var mark = cl.querySelector('svg') || cl;
    var lr = lg.getBoundingClientRect(), mr = mark.getBoundingClientRect(), cr = cl.getBoundingClientRect();
    if (!lr.height || !mr.height) return;
    var delta = (lr.top + lr.height / 2) - (mr.top + mr.height / 2);
    if (Math.abs(delta) < 0.5) return;                       // already aligned, avoid jitter
    cl.style.setProperty('top', Math.round(cr.top + delta) + 'px', 'important');
  }, 200);
})();

/* ===== core-6-campaign-guard.js ===== */
// Shared by both sites: the campaign list page lives on the FitTalk company site today and the
// ItZip site keeps the same guard, so the path comes from campaignPath in the brand file.
(function () {
  var CAMPAIGN_PATH = (window.FIT_BRAND || {}).campaignPath || '/about';
  var KEY = 'fitCampaignReloaded';
  var ready = false;
  var seenAway = location.pathname.indexOf(CAMPAIGN_PATH) !== 0;
  setTimeout(function () { ready = true; }, 1500);
  function guard() {
    if (location.pathname.indexOf(CAMPAIGN_PATH) !== 0) {
      seenAway = true;
      try { sessionStorage.removeItem(KEY); } catch (e) {}   // left the page, arm it again
      return;
    }
    if (!seenAway) return;                                   // original full load: widget handles it
    if (!ready) return;                                      // too early to judge on a full load
    if (window.FIT_CAMPAIGN_READY) return;                   // widget script ran, list is being built
    if (document.querySelector('#ftclGrid .ftcl-card')) return; // list already on screen
    try {
      if (sessionStorage.getItem(KEY)) return;               // already reloaded once, do not loop
      sessionStorage.setItem(KEY, '1');
    } catch (e) { return; }                                  // no sessionStorage, never risk a loop
    location.reload();
  }
  function wrap(name) {
    var orig = history[name];
    if (!orig) return;
    history[name] = function () {
      var r = orig.apply(this, arguments);
      guard();                                               // run at once so the wrong view barely shows
      return r;
    };
  }
  wrap('pushState');
  wrap('replaceState');
  window.addEventListener('popstate', guard);
  setInterval(guard, 200);                                   // catches navigations the hooks above miss
})();

/* ===== core-5-autofit.js ===== */
(function () {
  var CFG = {
    include: '[data-type="code"] iframe',
    excludeSrc: ['banner', 'bnDress', 'youtube', 'ads', 'pay', 'checkout']  // secondary safety net
  };

  var seen = new WeakMap();         // iframe -> last applied height and ratio

  function isExcluded(fr) {
    var s = ((fr.getAttribute('src') || 0) + ' ' + (fr.id || 0) + ' ' + (fr.className || 0)).toLowerCase();
    for (var i = 0; i < CFG.excludeSrc.length; i++) {
      if (s.indexOf(CFG.excludeSrc[i].toLowerCase()) !== -1) return true;
    }
    return false;
  }

  // Qshop draws the whole page as one canvas and scales it: --site-ratio is the factor.
  // There are two canvases - desktop is drawn at 1280px, mobile at 374px - and whichever
  // applies gets stretched to fill the window. A 1024 tablet is the desktop canvas at 0.8,
  // a 768 tablet is the MOBILE canvas blown up to 2.05. Section heights, fonts and images
  // all follow that factor. A code widget is the only thing that does not, because it
  // lives in an iframe with its own viewport: at 0.8 it draws too big and covers the next
  // section, at 2.05 it draws a phone-sized widget in a section built for 2x and leaves a
  // screen of white space. Same bug, both directions.
  function siteRatio() {
    var v = parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--site-ratio'));
    return (v > 0.05 && v < 20) ? v : 1;
  }

  function plain(R) { return Math.abs(R - 1) < 0.02; }

  // Lay the widget out at the width its canvas was drawn at, then scale the result -
  // exactly what Qshop does with everything else on the page.
  function applyScale(fr, R) {
    if (plain(R)) {
      if (fr.style.transform) {
        fr.style.removeProperty('width');
        fr.style.removeProperty('transform');
        fr.style.removeProperty('transform-origin');
        fr.style.removeProperty('flex-shrink');
      }
      return;
    }
    var want = 'scale(' + R + ')';
    if (fr.style.transform === want) return;
    fr.style.flexShrink = '0';   // the iframe is a flex item: without this it shrinks straight back
    fr.style.width = (100 / R) + '%';
    fr.style.transformOrigin = 'top left';
    fr.style.transform = want;
  }

  function innerHeight(doc) {
    var b = doc.body, e = doc.documentElement;
    return Math.max(
      b ? b.scrollHeight : 0, b ? b.offsetHeight : 0,
      e ? e.scrollHeight : 0, e ? e.offsetHeight : 0
    );
  }

  // scrollHeight ratchets: once we made the iframe tall, the document inside can never
  // report anything smaller, so a widget that becomes shorter (window widened, cards back
  // on one row) would keep the old height forever. Where the bottom of the last child is
  // clearly higher than that, trust the children instead - that number can go down.
  function contentHeight(doc) {
    var b = doc.body, win = doc.defaultView;
    if (!b || !win) return 0;
    var top = b.getBoundingClientRect().top, max = 0, kids = b.children;
    for (var i = 0; i < kids.length; i++) {
      var c = kids[i], tag = c.tagName;
      if (tag === 'SCRIPT' || tag === 'STYLE' || tag === 'LINK') continue;
      var cs = win.getComputedStyle(c);
      if (cs.display === 'none' || cs.position === 'fixed') continue;
      var bottom = c.getBoundingClientRect().bottom - top + (parseFloat(cs.marginBottom) || 0);
      if (bottom > max) max = bottom;
    }
    if (max <= 0) return 0;
    return Math.round(max + (parseFloat(win.getComputedStyle(b).paddingBottom) || 0));
  }

  function measure(doc) {
    var h = innerHeight(doc), c = contentHeight(doc);
    return (c > 0 && c < h - 8) ? c : h;   // only the shrink direction needs the child walk
  }

  function codeSlot(fr) {
    var el = fr.parentNode, hops = 0;
    while (el && el.nodeType === 1 && hops < 6) {
      if (el.getAttribute && el.getAttribute('data-type') === 'code') return el;
      el = el.parentNode; hops++;
    }
    return null;
  }

  // Last line of defence. A widget that still needs more room than its slot does not push
  // anything down - it just paints over the section below. Grow the section by whatever
  // hangs out the bottom so the page stays stacked instead of overlapping.
  function guard(fr) {
    var slot = codeSlot(fr);
    if (!slot) return;
    var grid = slot.parentNode;
    if (!grid || grid.nodeType !== 1 || !window.getComputedStyle) return;
    var gcs = window.getComputedStyle(grid);
    if (gcs.display.indexOf('grid') === -1) return;

    if (grid.__ftPad === undefined) grid.__ftPad = parseFloat(gcs.paddingBottom) || 0;
    grid.style.paddingBottom = grid.__ftPad + 'px';      // measure without our own padding

    var bottom = grid.getBoundingClientRect().bottom, over = 0, kids = grid.children;
    for (var i = 0; i < kids.length; i++) {
      var d = kids[i].getBoundingClientRect().bottom - bottom;
      if (d > over) over = d;
    }
    if (over > 1) grid.style.paddingBottom = (grid.__ftPad + Math.ceil(over)) + 'px';
  }

  function fit(fr) {
    if (isExcluded(fr)) return;
    var doc;
    try { doc = fr.contentDocument; } catch (e) { return; }   // cross-origin -> skip
    if (!doc || !doc.body) return;

    var R = siteRatio();
    applyScale(fr, R);          // width first, so the height below is measured on it

    var h = measure(doc);
    if (h <= 0) return;

    var key = h + 'x' + R;
    if (seen.get(fr) !== key) {
      seen.set(fr, key);

      fr.style.height = h + 'px';
      fr.style.minHeight = '0';
      fr.style.maxHeight = 'none';
      fr.style.overflow = 'hidden';
      // scale() is paint only - the box still takes h px of the page, so hand the rest
      // over (or give it back, when R is below 1) through the margin.
      if (plain(R)) fr.style.removeProperty('margin-bottom');
      else fr.style.marginBottom = Math.round(h * (R - 1)) + 'px';
      fr.setAttribute('scrolling', 'no');
      try { doc.documentElement.style.overflow = 'hidden'; doc.body.style.overflow = 'hidden'; } catch (e) {}

      unlockChain(fr);   // release fixed height so the grid row grows and pushes siblings down
    }

    guard(fr);           // the slot itself never grows, so give the section room for the spill
  }

  function unlockChain(fr) {
    var el = fr.parentNode, hops = 0;
    while (el && el.nodeType === 1 && hops < 6) {
      el.style.height = 'auto';
      el.style.minHeight = '0';
      el.style.maxHeight = 'none';
      el.style.overflow = 'visible';
      if (el.getAttribute && el.getAttribute('data-type') === 'code') {
        el.style.alignSelf = 'start';   // sit at top of the cell and grow with content
        break;
      }
      el = el.parentNode; hops++;
    }
  }

  function targets() {
    return CFG.include ? document.querySelectorAll(CFG.include) : document.getElementsByTagName('iframe');
  }

  function fitAll() {
    var list = targets();
    for (var i = 0; i < list.length; i++) fit(list[i]);
  }

  function hook(fr) {
    var doc;
    try { doc = fr.contentDocument; } catch (e) { return; }
    if (!doc || !doc.body) return;
    if (window.ResizeObserver && !doc.__ftRO) {
      doc.__ftRO = new ResizeObserver(function () { fit(fr); });
      doc.__ftRO.observe(doc.documentElement);
      doc.__ftRO.observe(doc.body);
    }
  }

  function watch(fr) {
    if (seen.has(fr)) return;
    seen.set(fr, 0);
    fr.addEventListener('load', function () { hook(fr); fit(fr); });
    hook(fr); fit(fr);
  }

  function scan() {
    var list = targets();
    for (var i = 0; i < list.length; i++) watch(list[i]);
  }

  window.addEventListener('resize', fitAll);
  window.addEventListener('load', function () { scan(); fitAll(); });
  document.addEventListener('DOMContentLoaded', scan);
  [100, 400, 900, 1800, 3000].forEach(function (t) { setTimeout(function () { scan(); fitAll(); }, t); });

  try {
    new MutationObserver(function () { scan(); }).observe(
      document.documentElement, { childList: true, subtree: true }
    );
  } catch (e) {}

  window.addEventListener('message', function (e) {
    var d = e.data;
    if (!d || d.type !== 'ftEmbedHeight') return;
    var list = document.getElementsByTagName('iframe');
    for (var i = 0; i < list.length; i++) {
      if (list[i].contentWindow === e.source) {
        list[i].style.height = d.height + 'px';
        list[i].style.overflow = 'hidden';
        list[i].setAttribute('scrolling', 'no');
        guard(list[i]);
        break;
      }
    }
  });

  scan();
})();

/* ===== itzip-0-site.js ===== */
(function () {
  // Per-site values for the reservation flow.
  //
  // Every per-site number lives in one table on the contact page:
  //
  //     번호 | 현장명              | 대표번호   | 휴대폰 번호
  //     1    | 오산 헤리티지 자이   | 1111-1111 | 010-1111-1111, 010-2222-2222
  //
  // That page is already loaded by the reservation modal, so one table covers every site
  // and nothing has to be planted in the product pages themselves.
  //
  // 대표번호 is the number the consult buttons dial, so only the first one there is used.
  // 휴대폰 번호 is who the notification text goes to and may name several people, comma
  // separated. Every one of them rides along in the webhook, so no lookup step is needed.
  //
  // Columns are matched by their heading, so their order can change. Without headings the
  // code falls back to reading the row left to right. Values are passed through exactly as
  // written - hyphens included, since Google Sheets would otherwise eat the leading zero.
  var B = window.FIT_BRAND || {};
  var CONTACT = B.contactPath || '/contact';
  var FALLBACK_TEL = B.tel || '1668-1561';
  var CACHE_KEY = 'fitSiteTels4';

  var tels = null;        // site name -> { tel, manager }, once the table has been read
  var loading = false;

  // Hyphens optional, so a row typed without them still works. Eight to eleven digits
  // keeps the row-number column and stray figures out of it.
  function isPhone(s) {
    if (!/^[0-9][0-9-]*[0-9]$/.test(s)) return false;
    var n = s.replace(/[^0-9]/g, '').length;
    return n >= 8 && n <= 11;
  }

  // Collapse whitespace so a stray double space in the table still matches the title.
  function key(s) { return (s || '').replace(/\s+/g, ' ').trim(); }

  // One cell may name more than one number - that is how the 휴대폰 번호 column says to
  // text several people. Comma, slash, semicolon, pipe or plain space all separate, so it
  // does not matter how the row was typed. A number never contains any of them, so nothing
  // valid gets cut in half. Repeats are dropped by their digits, and what survives is
  // passed on exactly as written since Google Sheets would eat the leading zero.
  function phoneList(s) {
    var out = [], seen = {}, bits = key(s).split(/[\s,;/|]+/);
    for (var i = 0; i < bits.length; i++) {
      var b = bits[i];
      if (!isPhone(b)) continue;
      var d = b.replace(/[^0-9]/g, '');
      if (seen[d]) continue;
      seen[d] = 1;
      out.push(b);
    }
    return out;
  }

  // Locate the columns from the heading row. Returns -1 for anything not found.
  function headings(rows) {
    var idx = { name: -1, tel: -1, manager: -1 };
    for (var r = 0; r < rows.length && r < 3; r++) {
      var cells = rows[r].querySelectorAll('td,th');
      var hit = false;
      for (var c = 0; c < cells.length; c++) {
        var h = key(cells[c].textContent);
        if (idx.name < 0 && (h.indexOf('현장') >= 0 || h.indexOf('사이트') >= 0)) { idx.name = c; hit = true; }
        else if (idx.tel < 0 && h.indexOf('대표') >= 0) { idx.tel = c; hit = true; }
        else if (idx.manager < 0 && (h.indexOf('휴대') >= 0 || h.indexOf('수신') >= 0 || h.indexOf('담당') >= 0)) { idx.manager = c; hit = true; }
      }
      if (hit) break;
    }
    return idx;
  }

  function cellAt(cells, i) { return (i >= 0 && cells[i]) ? key(cells[i].textContent) : ''; }

  function parseDoc(doc) {
    var map = {};
    if (!doc) return map;
    var rows = doc.querySelectorAll('tr');
    var idx = headings(rows);
    for (var r = 0; r < rows.length; r++) {
      var cells = rows[r].querySelectorAll('td,th');
      var name = '', tel = '', manager = '';
      if (idx.name >= 0) {
        name = cellAt(cells, idx.name);
        tel = phoneList(cellAt(cells, idx.tel))[0] || '';          // buttons can only dial one
        manager = phoneList(cellAt(cells, idx.manager)).join(','); // the text goes to all of them
      } else {
        for (var c = 0; c < cells.length; c++) {
          var t = key(cells[c].textContent);
          if (!t) continue;
          var pl = phoneList(t);
          if (pl.length) {
            // No headings, so the first number found is 대표번호 and the rest are recipients.
            // A cell holding two numbers still lands right if the columns were merged.
            if (!tel) { tel = pl[0]; if (pl.length > 1) manager = pl.slice(1).join(','); }
            else if (!manager) manager = pl.join(',');
          }
          else if (!/^[0-9]+$/.test(t) && !name) { name = t; }   // skip the row-number column
        }
      }
      if (name && tel) map[name] = { tel: tel, manager: manager };
    }
    return map;
  }

  // The contact page is a single page app, so what the server returns is an empty shell -
  // fetching it and parsing the HTML finds no table at all. It has to be rendered in a
  // hidden iframe and read once the script on it has drawn the rows, which is the same
  // trick the reservation modal already uses to reach the form.
  function load() {
    if (tels || loading) return;
    // The common code runs on the contact page too, so opening that page in a frame from
    // there would load another copy of the common code, which would open another frame,
    // without end. Only a top level product page needs the table; everything else stops.
    if (window.top !== window.self || location.pathname.indexOf(CONTACT) === 0) { tels = {}; return; }
    loading = true;
    // The cache is a head start, not the answer. It fills the buttons immediately, and the
    // read below still runs and overwrites it. Without that, editing the table would have
    // no effect until the browser session ended, which is a trap while setting sites up.
    try {
      var cached = sessionStorage.getItem(CACHE_KEY);
      if (cached) {
        var m = JSON.parse(cached);
        for (var k in m) { tels = m; break; }   // only trust a non-empty cache
      }
    } catch (e) {}

    var frame = document.createElement('iframe');
    frame.setAttribute('aria-hidden', 'true');
    frame.style.cssText = 'position:fixed;top:0;left:0;width:1px;height:1px;border:0;opacity:0;pointer-events:none;z-index:-1';
    frame.src = CONTACT;
    var tries = 0;
    function finish(map) {
      var got = false;
      for (var k in map) { got = true; break; }
      if (got) {
        tels = map;                                   // fresh read wins over the cache
        try { sessionStorage.setItem(CACHE_KEY, JSON.stringify(map)); } catch (e) {}
      } else if (!tels) {
        tels = {};                                    // nothing read and nothing cached
      }                                               // an empty read never overwrites a cache
      loading = false;
      if (frame.parentNode) frame.parentNode.removeChild(frame);
    }
    function peek() {
      var doc = null;
      try { doc = frame.contentDocument; } catch (e) {}
      if (doc && doc.body) {
        var map = parseDoc(doc);
        for (var k in map) { finish(map); return; }   // rows have been drawn
      }
      if (++tries > 60) { finish({}); return; }       // about 12 seconds, then give up
      setTimeout(peek, 200);
    }
    (document.body || document.documentElement).appendChild(frame);
    setTimeout(peek, 200);
  }

  function siteName() {
    var h = document.querySelector('.productDetailPage h1');
    return h ? key(h.textContent) : '';
  }

  function row() {
    if (!tels) { load(); return null; }
    var n = siteName();
    return (n && tels[n]) ? tels[n] : null;
  }

  load();

  window.FIT_SITE = {
    // Consult number the buttons dial, and what gets logged as 대표번호.
    tel: function () { var x = row(); return (x && x.tel) || FALLBACK_TEL; },

    // Everyone the notification text is sent to, comma joined. One name is the common case
    // and reads as a plain number. Empty when the site is missing from the table, which is
    // the signal that a row still has to be added for it.
    managerPhone: function () { var x = row(); return (x && x.manager) || ''; },

    // The same list as an array, for anything that wants to walk the recipients.
    managerPhones: function () { var s = this.managerPhone(); return s ? s.split(',') : []; },

    // Whether the row was found. Lands in the 추출 경로 column, so a site that is
    // missing from the table can be spotted at a glance.
    telSource: function () { return row() ? 'table' : 'none'; },

    // Site name, taken from the product title. This is the sheet lookup key and also
    // the key into the table above, so the two have to agree.
    name: siteName,

    // Full URL including the query string, so ad tracking params survive.
    url: function () { return location.href; }
  };

})();

/* ===== itzip-2-landing.js ===== */
(function () {
  // If this footer ever gets injected twice, keep one interval and one observer.
  if (window.fitLandingUp) return;
  window.fitLandingUp = 1;

  var FIT_HIDE_HERO    = true;
  var FIT_CLOAK_MS     = 900;   // hard ceiling on how long the detail page may stay cloaked
  // Consult number comes from the hidden marker on the detail page, read fresh every
  // time. The buttons are built before the detail HTML finishes loading, so a value
  // captured once at startup would be the fallback forever.
  function curTel(){
    return (window.FIT_SITE ? window.FIT_SITE.tel() : '') || (window.FIT_BRAND || {}).tel || '1668-1561';
  }
  var FIT_RESERVE_LABEL= '\ubc29\ubb38 \uc608\uc57d';        // visit reservation
  // \uc0c1\ub2f4 \ubc84\ud2bc\uc740 "\uc0c1\ub2f4 \ubb38\uc758" \ub300\uc2e0 \uadf8 \ud604\uc7a5\uc758 \ub300\ud45c\ubc88\ud638\ub97c \ub2f5\ub2c8\ub2e4. \uc67c\ucabd \uc218\ud654\uae30\ub294 fill \uc774
  // currentColor \ub77c \ubc84\ud2bc \uc0c9\uc774 \ub4a4\uc9d1\ud600\ub3c4(paintBtn) \uae00\uc790\uc640 \uac19\uc774 \ub530\ub77c\uc635\ub2c8\ub2e4. width/height \ub97c
  // px \uc774 \uc544\ub2c8\ub77c em \uc73c\ub85c \uc900 \uac83\uc740 \uae00\uc790 \ud06c\uae30\uc5d0 \ub9de\ucdb0 \uac19\uc774 \uc790\ub77c\ub77c\ub294 \ub73b\uc785\ub2c8\ub2e4.
  // \uc218\ud654\uae30 \uac00\uc6b4\ub370 \uc190\uc7a1\uc774\ub294 \uc77c\ubd80\ub7ec \uad75\uac8c \uadf8\ub838\uc2b5\ub2c8\ub2e4. \ud754\ud55c Material call \uc544\uc774\ucf58\uc740 \uc774 \ubd80\ubd84\uc774
  // 15px \ub85c \uc904\uba74 \uc2e4\ucc98\ub7fc \uc587\uc544\uc838\uc11c \ubb34\uc2a8 \uadf8\ub9bc\uc778\uc9c0 \uc548 \ubcf4\uc785\ub2c8\ub2e4. \uc88c\ud45c\ub294 24 \uac00 \uc544\ub2c8\ub77c 16 \uce78
  // \uae30\uc900\uc774\ub77c(viewBox) \uac19\uc740 em \uc5d0\uc11c \uadf8\ub9bc\uc774 \uc870\uae08 \ub354 \ud06c\uac8c \ucc39\ub2c8\ub2e4.
  var TEL_SVG = '<svg viewBox="0 0 16 16" fill="currentColor" aria-hidden="true" style="width:1.05em;height:1.05em;flex:0 0 auto;display:block"><path d="M3.9 1.1a1.2 1.2 0 0 0-1.8-.1L1 2.1C.2 2.9 0 4.1.4 5.1a19 19 0 0 0 4.4 6.6 19 19 0 0 0 6.1 4.1c1 .4 2.2.2 3-.6l1.1-1.1a1.2 1.2 0 0 0-.1-1.8l-2.5-1.9c-.4-.3-1-.4-1.5-.3l-1.8.5c-.4.1-.9 0-1.2-.3L5.6 7.1c-.3-.3-.4-.8-.3-1.2l.5-1.8c.1-.5 0-1.1-.3-1.5L3.9 1.1z"/></svg>';

  // Everything scoped inside .productDetailPage keys off that element alone, NOT off
  // body.fit-landing. The body class is only set from inside landingTidy, so hanging the
  // rules on it meant the stock reviews/tabs/order bar stayed visible until the first
  // tick -- that wait was a chunk of the flash on entry.
  var st = document.createElement('style');
  st.textContent =
      '.productDetailPage #review,'
    + '.productDetailPage #qna,'
    + '.productDetailPage #attr{display:none !important}'
    + '.productDetailPage #nav nav > div:nth-child(n+2){display:none !important}'
    + '.productDetailPage #detail .ck-content{text-align:center !important}'
    + '.productDetailPage #detail figure{width:auto !important;max-width:100% !important;margin-left:auto !important;margin-right:auto !important;float:none !important}'
    + '.productDetailPage #detail img{width:auto !important;max-width:100% !important;height:auto !important;display:block !important;margin-left:auto !important;margin-right:auto !important}'
    + '.productDetailPage #nav,.productDetailPage #nav > div{position:static !important;top:auto !important}'   // unstick the tab/divider bar (QShop made it sticky on scroll)
    // The last surviving tab label is dead weight. The other tabs are already hidden above, so
    // it labels nothing and only pushes the page down. Drop the text and squash the row to a
    // single rule between the address and the detail body.
    // The rule has to be the border on nav itself, not the one on the active tab. The active
    // class moves as you scroll through the sections, so a line drawn on it comes and goes.
    // nav is always there, so its border cannot blink out. QShop ships it at 2px and a tenth
    // of black; 1px at .14 keeps it visible while reading as a hairline rather than a divider.
    // The row is left at the default 20px below the address block - closer than that and the
    // rule crowds the text.
    + '.productDetailPage #nav nav > div > span{display:none !important}'
    + '.productDetailPage #nav nav > div{height:0 !important;min-height:0 !important;padding:0 !important;margin:0 !important;border-bottom:0 !important}'
    + '.productDetailPage #nav nav{height:0 !important;min-height:0 !important;padding:0 !important;border-bottom:1px solid rgba(22,22,22,.14) !important}'
    + '@media (max-width:768px){.productDetailPage .css-8jwieb{border-top:0 !important;border-bottom:0 !important}}'   // kill the address block top/bottom lines on mobile
    // Mobile full-bleed for the detail body. QShop puts 24px side padding on the page container
    // and the title and address need it, so only the detail body breaks out of it.
    // The breakout has to sit on .ck-content, not on the images. Two reasons:
    //   - .ck-content is overflow:hidden, so a wider image inside it is simply clipped. Layout
    //     boxes still report the full width, so this only shows on a real screen.
    //   - figure.image is display:table, so a percentage margin on the image resolves against a
    //     shrink-to-fit box rather than the container.
    // 100vw + margin calc(50% - 50vw) cancels the padding whatever it is, without naming any of
    // the hashed QShop class names, which change whenever they redeploy. body already has
    // overflow-x:hidden so nothing scrolls sideways.
    + '@media (max-width:768px){'
    +   '.productDetailPage #detail .ck-content{width:100vw !important;max-width:100vw !important;margin-left:calc(50% - 50vw) !important;margin-right:calc(50% - 50vw) !important;padding-left:0 !important;padding-right:0 !important;overflow:visible !important}'
    +   '.productDetailPage #detail figure.image{display:block !important;width:100% !important;max-width:100% !important;margin-left:0 !important;margin-right:0 !important}'
    +   '.productDetailPage #detail img{width:100% !important;max-width:100% !important;margin-left:0 !important;margin-right:0 !important}'
    // The youtube cards keep the gutter they had before, so their rounded corners do not sit on
    // the screen edge. Selector is one class deeper than the block rules above, so order is moot.
    +   '.productDetailPage #detail .izv-row{padding-left:24px !important;padding-right:24px !important;box-sizing:border-box !important}'
    + '}'
    + 'body.fit-landing #dialog-root [type="mobile-order"]{display:none !important}'   // rendered OUTSIDE .productDetailPage, so this one still needs the body class
    // The QShop floating content (the back-to-top button) is a fixed div sitting directly on
    // body at bottom:15px with z-index 100000. Our mobile CTA bar is 61px tall and draws above
    // it, so on a phone the button was completely buried - elementFromPoint over it returned the
    // consult button, not the arrow. It looked like the button was missing on product pages only,
    // because that bar exists only there. Lift it clear of the bar: 61 + the 15px it already had.
    // Matched by the arrow icon since the wrapper carries nothing but a hashed class name. If the
    // icon is ever changed in the QShop floating settings, update the class here to match.
    + '@media (max-width:768px){body.fit-landing > div:has(.fa-arrow-up){bottom:76px !important}}'
    // Cloak. The gallery, price, delivery row and buy bar can only be removed by JS once
    // QShop has rendered them, so hold the page invisible until the first pass finishes.
    // visibility (not opacity) so no stacking context is created -- an opacity below 1
    // would re-anchor the fixed bottom bar while it faded in.
    // revealPd sets data-fit-ready, and the watchdog in tickTidy sets it after
    // FIT_CLOAK_MS whatever happens, so a QShop markup change can never leave it blank.
    + '.productDetailPage:not([data-fit-ready]){visibility:hidden !important}';
  (document.head || document.documentElement).appendChild(st);

  // The reservation UI is the custom modal in window.fitReserve (defined further down
  // in this footer). It is always present, so there is no fallback path here.
  function openReserve(){
    if (window.fitReserve) window.fitReserve();
  }

  // 큐샵이 자기 인라인 스타일을 계속 다시 박으므로 이 조각의 스타일은 전부
  // !important 로 나갑니다. 그 한 줄이 마흔 번 넘게 나오는데 한 번에 50 바이트라
  // 공통코드 한도(65535)에 그대로 얹혀서, 짧은 도우미 하나로 묶었습니다.
  function P(el, k, v){ el.style.setProperty(k, v, 'important'); }

  function applyBtnBox(el){
    P(el, 'display', 'inline-block');
    P(el, 'box-sizing', 'border-box');
    P(el, 'padding', '12px 26px');
    P(el, 'font-size', '15px');
    P(el, 'font-weight', '700');
    P(el, 'line-height', '1');
    P(el, 'white-space', 'nowrap');
    P(el, 'width', 'auto');
    P(el, 'height', 'auto');
    P(el, 'flex', '0 0 auto');
    P(el, 'border', '1px solid #3700ff');
    P(el, 'border-radius', '0');
    P(el, 'box-shadow', 'none');
    P(el, 'cursor', 'pointer');
    P(el, 'text-decoration', 'none');
    P(el, 'opacity', '1');
    P(el, 'pointer-events', 'auto');
  }
  function paintBtn(el, filled){
    P(el, 'background-color', filled ? '#3700ff' : '#ffffff');
    P(el, 'color', filled ? '#ffffff' : '#3700ff');
  }
  // 수화기와 번호를 한 줄에 세웁니다. 모바일 하단 바에서는 버튼이 flex:1 로 늘어나므로
  // text-align 이 아니라 justify-content 가 가운데 정렬을 맡습니다.
  function consultBox(el){
    P(el, 'display', 'inline-flex');
    P(el, 'align-items', 'center');
    P(el, 'justify-content', 'center');
    P(el, 'gap', '7px');
  }
  // 번호는 현장마다 다르고 상세 HTML 이 늦게 도착하므로 매 tick 다시 씁니다. 지금 보이는
  // 것이 이미 그 번호면 그냥 돌아섭니다. 표시 자체를 보고 판정하는 것이라(예전의
  // textContent 비교와 같은 성질) 큐샵이 자기 버튼을 다시 그려 놓아도 다음 tick 에
  // 저절로 되돌아옵니다.
  // 아이콘은 우리가 쓴 문자열뿐이고, 시트에서 온 번호는 textContent 로만 넣습니다.
  function setConsult(el, tel){
    if (el.textContent === tel && el.querySelector('svg')) return;
    el.innerHTML = TEL_SVG;
    var s = document.createElement('span');
    s.textContent = tel;
    el.appendChild(s);
  }
  function mkBtn(kind){
    var filled = (kind === 'reserve');
    var el = document.createElement(kind === 'consult' ? 'a' : 'button');
    applyBtnBox(el);
    P(el, 'transition', 'background-color .15s ease,color .15s ease');
    paintBtn(el, filled);
    if (kind === 'reserve') el.textContent = FIT_RESERVE_LABEL;
    else { consultBox(el); setConsult(el, curTel()); }
    if (kind === 'consult'){ el.className = 'fit-consult'; el.href = 'tel:' + curTel(); }
    else { el.type = 'button'; el.addEventListener('click', function (e) { e.preventDefault(); e.stopPropagation(); openReserve(); }); }
    el.addEventListener('mouseenter', function () { paintBtn(el, !filled); });
    el.addEventListener('mouseleave', function () { paintBtn(el, filled); });
    return el;
  }

  var topWrap = document.getElementById('fit-top-ctas');
  if (!topWrap){
    topWrap = document.createElement('div');
    topWrap.id = 'fit-top-ctas';
    topWrap.style.cssText = 'position:absolute;right:0;top:0;z-index:5;display:flex;gap:10px;align-items:center';
    topWrap.appendChild(mkBtn('reserve'));
    topWrap.appendChild(mkBtn('consult'));
  }

  var mcta = document.getElementById('fit-mcta');
  if (!mcta){
    mcta = document.createElement('div');
    mcta.id = 'fit-mcta';
    mcta.style.cssText = 'position:fixed;left:0;right:0;bottom:0;z-index:2147482500;display:none;gap:8px;padding:10px 14px;background:#ffffff;box-shadow:0 -2px 12px #0000001f;box-sizing:border-box';
    var mRes = mkBtn('reserve'), mCon = mkBtn('consult');
    P(mRes, 'flex', '1'); P(mRes, 'text-align', 'center');
    P(mCon, 'flex', '1'); P(mCon, 'text-align', 'center');
    mcta.appendChild(mRes); mcta.appendChild(mCon);
    (document.body || document.documentElement).appendChild(mcta);
  }

  // 상세페이지 우하단에 있던 "맨 위로" 동그란 버튼(#fit-totop)은 2026-08-13 에 뺐습니다.

  function hide(el){ if (el) P(el, 'display', 'none'); }
  function isPriceText(t){
    t = (t || '').trim();
    if (t.length < 2 || t.charAt(t.length - 1) !== '\uc6d0') return false;
    var body = t.slice(0, -1);
    for (var i = 0; i < body.length; i++){
      var c = body.charAt(i);
      if ((c < '0' || c > '9') && c !== ',') return false;
    }
    return true;
  }
  function findBar(root){
    var btn = root.querySelector('button');
    if (btn){
      var el = btn;
      while (el && el !== root){
        var pos = '';
        try { pos = getComputedStyle(el).position; } catch (e) {}
        if (pos === 'fixed') return el;
        el = el.parentElement;
      }
    }
    var all = root.querySelectorAll('*');
    for (var i = 0; i < all.length; i++){
      var p2 = '';
      try { p2 = getComputedStyle(all[i]).position; } catch (e) {}
      if (p2 === 'fixed') return all[i];
    }
    return null;
  }
  function keepPath(container, keepEl){
    function rec(node){
      for (var i = 0; i < node.children.length; i++){
        var c = node.children[i];
        if (c === keepEl) continue;
        if (c.contains(keepEl)) rec(c);
        else hide(c);
      }
    }
    rec(container);
  }
  function isHover(el){ try { return !!(el.matches && el.matches(':hover')); } catch (e) { return false; } }
  function dressBarConsult(cta){
    cta.removeAttribute('disabled');
    var lbl = cta.querySelector('p') || cta;
    setConsult(lbl, curTel());
    var filled = isHover(cta);
    applyBtnBox(cta);
    consultBox(cta);   // applyBtnBox 의 inline-block 을 덮어야 하므로 반드시 뒤에
    paintBtn(cta, filled);
    if (lbl && lbl !== cta){
      consultBox(lbl);
      P(lbl, 'color', filled ? '#ffffff' : '#3700ff');
      P(lbl, 'white-space', 'nowrap');
      P(lbl, 'margin', '0');
    }
    if (!cta.getAttribute('data-fit-cta')){
      cta.setAttribute('data-fit-cta', '1');
      cta.addEventListener('click', function (e) { e.preventDefault(); e.stopPropagation(); window.location.href = 'tel:' + curTel(); });
      cta.addEventListener('mouseenter', function () { dressBarConsult(cta); });
      cta.addEventListener('mouseleave', function () { dressBarConsult(cta); });
    }
  }
  function dressBar(bar){
    var first = bar.children[0];
    var cta = first ? first.querySelector('button:not(.fit-bar-reserve)') : null;
    if (!cta) return;   // mid-rerender tick: skip, the 300ms loop retries
    first.style.removeProperty('display');   // self-heal if a past tick hid the row
    var par = cta.parentElement;
    if (par){
      P(par, 'display', 'flex');
      P(par, 'gap', '10px');
      P(par, 'align-items', 'center');
      P(par, 'background', 'transparent');
      P(par, 'box-shadow', 'none');
      var reserves = bar.querySelectorAll('.fit-bar-reserve');   // scope the check to the WHOLE bar
      if (reserves.length === 0){
        var res = mkBtn('reserve');
        res.className = 'fit-bar-reserve';
        par.insertBefore(res, cta);   // reserve to the LEFT of consult
      } else {
        for (var ri = 1; ri < reserves.length; ri++) reserves[ri].remove();   // drop any duplicates
      }
      for (var ci = 0; ci < par.children.length; ci++){
        var pc = par.children[ci];
        if (pc.tagName !== 'BUTTON' && pc.querySelector && pc.querySelector('svg')) hide(pc);
      }
    }
    for (var bi = 1; bi < bar.children.length; bi++) hide(bar.children[bi]);
    dressBarConsult(cta);
  }
  function setBarAddr(bar, addr){
    if (!addr) return;
    var els = bar.querySelectorAll('*');
    for (var i = 0; i < els.length; i++){
      var e = els[i];
      if (e.children.length === 0 && isPriceText(e.textContent)){
        if (e.textContent !== addr) e.textContent = addr;
        P(e, 'font-weight', '400');
        P(e, 'font-size', '14px');
        P(e, 'color', '#666666');
        return;
      }
    }
  }

  function landingTidy(){
    var pd = document.querySelector('.productDetailPage');
    if (document.body) document.body.classList.toggle('fit-landing', !!pd);
    if (!pd){
      // 상세페이지를 벗어나면 하단 바를 반드시 끕니다. 켜는 코드가 아래 상세페이지 분기
      // 안에만 있어서, SPA 뒤로가기로 홈에 와도 바는 살아남아 그대로 떠 있었습니다.
      // (#fit-top-ctas 는 상세페이지 DOM 안에 붙으므로 페이지와 함께 사라집니다.)
      if (mcta) P(mcta, 'display','none');
      return true;
    }
    var sw = pd.querySelector('.swiper');
    if (!sw) return false;   // markup not rendered yet -- stay cloaked, the caller retries
    var node = sw, row = null;
    for (var i = 0; i < 8 && node && node.parentElement; i++){
      var p = node.parentElement, disp = '';
      try { disp = getComputedStyle(p).display; } catch (e) {}
      if (p.children.length >= 2 && disp.indexOf('flex') >= 0){ row = p; break; }
      node = p;
    }
    if (!row) return false;   // same -- the two column row is not laid out yet
    var gallery = null, info = null;
    for (var j = 0; j < row.children.length; j++){
      if (row.children[j].contains(sw)) gallery = row.children[j];
      else info = row.children[j];
    }
    if (FIT_HIDE_HERO && gallery){
      hide(gallery);
      if (info){ P(info, 'flex', '1'); P(info, 'width', '100%'); }
    }
    if (info){
      var pageAddr = '', stickyBar = null, addrBlock = null;
      var kids = info.children;
      for (var k = 0; k < kids.length; k++){
        var ch = kids[k];
        if (ch.id === 'fit-top-ctas') continue;
        if (ch.querySelector && ch.querySelector('h1')) continue;
        if (ch.id === 'form-review') { hide(ch); continue; }
        if (ch.querySelector && ch.querySelector('button')) {
          var bar = findBar(ch);
          if (bar){ keepPath(ch, bar); dressBar(bar); stickyBar = bar; }
          continue;
        }
        if (isPriceText(ch.textContent)) { hide(ch); continue; }
        var subs = ch.children;
        for (var m = 0; m < subs.length; m++){
          var stx = (subs[m].textContent || '').trim();
          if (stx.indexOf('\ubc30\uc1a1') === 0) { hide(subs[m]); continue; }
          if (stx && !pageAddr) pageAddr = stx;
        }
        if (!pageAddr){ var tx = (ch.textContent || '').trim(); if (tx) pageAddr = tx; }
        addrBlock = ch;   // the kept block = the address block (has mobile-only top/bottom borders)
        P(ch, 'margin-top', '0');
        var inner = ch.querySelector('div');
        if (inner) P(inner, 'padding', '0');
      }
      var h1 = info.querySelector('h1');
      if (h1 && h1.nextElementSibling) hide(h1.nextElementSibling);
      P(info, 'position', 'relative');
      if (topWrap.parentElement !== info) info.appendChild(topWrap);
      if (stickyBar) setBarAddr(stickyBar, pageAddr);
    }
    var navEl = pd.querySelector('#nav nav');
    if (navEl){
      P(navEl, 'display', 'flex');
      P(navEl, 'justify-content', 'center');
      var tabs = navEl.children;
      for (var n = 0; n < tabs.length; n++){
        if (n === 0){ P(tabs[n], 'flex', '1'); P(tabs[n], 'text-align', 'center'); }
        else { P(tabs[n], 'display', 'none'); }
      }
    }
    var mobile = (document.documentElement.clientWidth || window.innerWidth || 0) <= 768;
    if (topWrap) P(topWrap, 'display', mobile ? 'none' : 'flex');
    if (mcta) P(mcta, 'display', mobile ? 'flex' : 'none');
    var mh1 = info ? info.querySelector('h1') : null;
    if (mobile){
      if (info) P(info, 'text-align', 'center');
      if (mh1){ P(mh1, 'font-size', '26px'); P(mh1, 'margin', '6px 0 8px'); }
    } else {
      if (info) P(info, 'text-align', 'left');
      if (mh1){ mh1.style.removeProperty('font-size'); mh1.style.removeProperty('margin'); }
    }
    if (typeof addrBlock !== 'undefined' && addrBlock){
      if (mobile){ P(addrBlock, 'border-top', 'none'); P(addrBlock, 'border-bottom', 'none'); }
      else { addrBlock.style.removeProperty('border-top'); addrBlock.style.removeProperty('border-bottom'); }
    }
    // Re-point the consult links every tick. The marker lives in the detail HTML, which
    // can arrive after the buttons were built, so this is what makes the number stick.
    // 이제 글자도 번호라서 href 와 함께 표시도 다시 씁니다.
    var tel = curTel(), want = 'tel:' + tel;
    var links = document.querySelectorAll('a.fit-consult');
    for (var li = 0; li < links.length; li++){
      if (links[li].getAttribute('href') !== want) links[li].setAttribute('href', want);
      setConsult(links[li], tel);
    }
    return true;
  }

  function revealPd(pd){
    if (pd && !pd.hasAttribute('data-fit-ready')) pd.setAttribute('data-fit-ready', '');
  }
  // Single entry point. Runs the pass, then decides whether the page may be shown.
  // Every uncertain outcome reveals rather than hides: a thrown error reveals at once,
  // and a pass that keeps failing reveals anyway once FIT_CLOAK_MS is up. Worst case is
  // the old behaviour (stock layout visible), never a blank page.
  function tickTidy(){
    var pd = document.querySelector('.productDetailPage');
    if (pd && !pd.fitCloakAt) pd.fitCloakAt = new Date().getTime();
    var done = false;
    try { done = landingTidy(); } catch (e) { done = true; }
    if (pd && (done || new Date().getTime() - pd.fitCloakAt > FIT_CLOAK_MS)) revealPd(pd);
  }

  // Coalesce bursts of DOM changes into one pass on the next frame.
  var queued = false;
  function schedule(){
    if (queued) return;
    queued = true;
    var raf = window.requestAnimationFrame || function (f) { return setTimeout(f, 16); };
    raf(function () { queued = false; tickTidy(); });
  }

  setInterval(tickTidy, 300);   // backstop, unchanged
  // The observer is what removes the lag: it fires as soon as QShop renders the detail
  // markup, so the pass runs on the next frame instead of up to a poll interval later.
  // childList only, never attributes -- the pass itself sets styles, and watching those
  // would make it retrigger on its own work.
  try {
    new MutationObserver(schedule).observe(document.documentElement, { childList: true, subtree: true });
  } catch (e) {}
  window.addEventListener('popstate', schedule);
  // iOS 사파리는 뒤로가기를 bfcache 복원으로 처리하는 경우가 있어 popstate 가 안 옵니다.
  window.addEventListener('pageshow', schedule);
  // SPA links navigate with pushState, which fires no event of its own.
  try {
    var H = window.history, names = ['pushState', 'replaceState'];
    for (var hi = 0; hi < names.length; hi++){
      (function (n) {
        var orig = H[n];
        if (typeof orig !== 'function') return;
        H[n] = function () { var r = orig.apply(this, arguments); schedule(); return r; };
      })(names[hi]);
    }
  } catch (e) {}
  tickTidy();
})();

/* ===== itzip-5-media.js ===== */
(function () {
  // 상세설명(CKEditor) 안의 유튜브를 썸네일 카드 + 오버레이 재생으로 바꿉니다.
  //
  // 배경: 큐샵 상세설명 에디터는 직접 짜 넣은 div/iframe/style 을 저장할 때 전부 지웁니다.
  // 살아남는 것은 에디터 자기 ▶ 버튼이 만든 figure.media 뿐인데 그건 16:9 박스로 고정돼
  // 있어서 세로 숏츠가 가운데 쪼그라들고 좌우가 검게 남습니다. 그래서 그 figure 안을
  // 통째로 우리 카드로 갈아끼웁니다. 원래 iframe 은 없어지므로 페이지가 오히려 가벼워집니다.
  //
  // 상세설명에 넣는 방법은 하던 그대로입니다. 툴바 ▶ 버튼에
  //     https://www.youtube.com/watch?v=영상ID
  // 를 붙여넣기만 하면 됩니다. 숏츠 주소(/shorts/)는 에디터가 인식하지 못하므로 watch
  // 형식으로 바꿔서 넣어야 합니다. 세로인지 가로인지는 아래에서 알아서 봅니다.
  //
  // 배치 규칙
  //   가로형(롱폼) : 언제나 한 줄에 하나
  //   세로형(숏츠) : PC 는 한 줄에 둘, 모바일은 한 줄에 하나.
  //                  홀수면 짝 없는 마지막 하나가 한 줄을 다 씀
  //   폭은 랜딩 이미지와 같은 860 안에서만. 실제 배치는 css 의 .izv-row 가 합니다.
  //
  // 코드가 촘촘한 것은 취향이 아니라 큐샵 공통코드 65535 바이트 한도 때문입니다.
  // 주석은 빌드할 때 걷어내므로 설명은 여기 마음껏 답니다.
  if (window.fitMediaUp) return;      // 공통푸터는 페이지당 두 벌 실행됩니다
  window.fitMediaUp = 1;
  var Y = 'https://i.ytimg.com/vi/', N = ['oardefault', 'maxresdefault', 'hqdefault'];
  var KEY = 'AIzaSyARi62ar23ZrzdyP_Twi1rmg8c1yXL9c4g';   // 20 번 위젯과 같은 키. 리퍼러 제한됨
  var meta = {}, asked = {};          // 영상ID -> {t:제목, d:길이}
  function Q(s) { return document.querySelectorAll(s); }
  // watch?v= / youtu.be / embed / shorts 어느 형식으로 저장돼 있든 영상ID 11글자만.
  function vid(u) { var m = /(?:v=|be\/|embed\/|shorts\/)([\w-]{11})/.exec(u || ''); return m ? m[1] : ''; }
  // oardefault.jpg 는 영상 원본 비율 그대로의 프레임입니다. 숏츠면 720x1280, 가로 영상이면
  // 1280x720. 이 한 장이 두 가지를 한꺼번에 알려줍니다. 어느 쪽 영상인지, 그리고 카드에 깔
  // 포스터로 무엇을 쓸지. 없으면 16:9 썸네일로 물러섭니다. 유튜브가 빈 썸네일 자리에
  // 120x90 회색 판을 주기도 해서 너무 작으면 실패로 봅니다.
  function post(id, cb) {
    var i = 0, m = new Image();
    m.onerror = function () { if (++i >= N.length) return cb('', 0); m.src = Y + id + '/' + N[i] + '.jpg'; };
    m.onload = function () { if (m.naturalWidth < 200) return m.onerror(); cb(m.src, m.naturalHeight > m.naturalWidth); };
    m.src = Y + id + '/' + N[0] + '.jpg';
  }
  // ISO8601 재생시간(PT6M23S) -> 6:23
  function dur(s) {
    var m = /(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/.exec(s.slice(2)), h = +m[1] || 0, x = +m[2] || 0, y = +m[3] || 0;
    function p(v) { return (v < 10 ? '0' : '') + v; }
    return h ? h + ':' + p(x) + ':' + p(y) : x + ':' + p(y);
  }
  // 제목과 길이는 한 번에 몰아서 받습니다. 페이지에 영상이 몇 개든 요청 한 번입니다.
  // 실패해도(키 제한, 할당량, 오프라인) 제목과 배지만 안 붙고 나머지는 그대로 돕니다.
  function pull(ids) {
    if (!ids.length || !window.fetch) return;
    fetch('https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails&id=' + ids.join(',') + '&key=' + KEY)
      .then(function (r) { return r.json(); })
      .then(function (j) {
        (j.items || []).forEach(function (v) { meta[v.id] = { t: v.snippet.title, d: dur(v.contentDetails.duration) }; });
        paint();
      }).catch(function () {});
  }
  // 제목은 textContent 로 넣습니다. 유튜브에서 온 남의 글자를 innerHTML 로 넣지 않기 위해서입니다.
  function paint() {
    [].forEach.call(Q('figure.media[data-izv]'), function (f) {
      var m = meta[f.getAttribute('data-izv')], b, t, e;
      if (!m) return;
      b = f.querySelector('.izv-b'); t = f.querySelector('.izv-t');
      if (b && !b.querySelector('i')) { e = document.createElement('i'); e.textContent = m.d; b.appendChild(e); }
      if (t && !t.textContent) t.textContent = m.t;
    });
  }
  // 사이에 빈 문단만 있으면 붙어 있는 것으로 봅니다. 에디터에서 엔터를 치면 영상 사이에
  // 빈 p 가 남기 때문입니다. 이미지나 글이 끼면 거기서 묶음이 끊깁니다. 사이에 있던 것들은
  // g 에 모아 뒀다가 묶음이 확정되면 지웁니다. 안 지우면 래퍼 밖에 빈 줄로 남습니다.
  function near(a, b, g) {
    for (var n = a.nextSibling; n; n = n.nextSibling) {
      if (n === b) return 1;
      if (n.nodeType != 1) { if ((n.nodeValue || '').replace(/\s/g, '')) return 0; }
      else if (n.querySelector('img,iframe,figure') || n.textContent.replace(/[\s ]/g, '')) return 0;
      g.push(n);
    }
    return 0;
  }
  // 붙어 있는 영상들을 우리 래퍼(div.izv-row) 하나에 담습니다. 폭 860 과 가운데 정렬,
  // 2단 배치는 전부 그 래퍼가 css 로 합니다. figure 에 인라인 margin:0 을 박는 이유는
  // css 주석에 적어 뒀습니다. 이미 담긴 묶음은 건너뛰므로 여러 번 불러도 안전합니다.
  function rows() {
    var f = Q('figure.media'), r = [], g, i, j;
    function flush() {
      if (r.length && r[0].parentNode.className != 'izv-row') {
        var w = document.createElement('div');
        w.className = 'izv-row';
        r[0].parentNode.insertBefore(w, r[0]);
        for (var k = 0; k < r.length; k++) { r[k].style.cssText = 'margin:0!important'; w.appendChild(r[k]); }
      }
      r = [];
    }
    for (i = 0; i < f.length; i++) {
      g = [];
      if (r.length && !near(r[r.length - 1], f[i], g)) flush();
      else for (j = 0; j < g.length; j++) { if (g[j].nodeType == 1) g[j].style.display = 'none'; else g[j].nodeValue = ''; }
      r.push(f[i]);
    }
    flush();
  }
  function scan() {
    var fresh = [];
    [].forEach.call(Q('figure.media div[data-oembed-url]'), function (d) {
      var g = d.parentNode, id = vid(d.getAttribute('data-oembed-url'));
      if (!id || g.getAttribute('data-izv')) return;
      g.setAttribute('data-izv', id);
      if (!asked[id]) { asked[id] = 1; fresh.push(id); }
      post(id, function (s, t) {
        g.className = 'media ' + (t ? 'izv-s' : 'izv-l');
        g.innerHTML = '<a class=izv><span class=izv-b>' +
          (s ? '<img loading=lazy alt="" src="' + s + '">' : '') + '</span><span class=izv-t></span></a>';
        rows(); paint();
      });
    });
    if (fresh.length) pull(fresh);
  }
  // 클릭하면 유튜브로 나가지도, 덮는 창을 띄우지도 않고 그 카드 자리에서 바로 재생합니다.
  // 포스터(img)와 배지(i)는 지우지 않고 그 위에 iframe 을 덮기만 합니다. 되돌릴 때 iframe
  // 하나만 걷어내면 원래 카드가 그대로 돌아오고, iframe 이 사라지는 것이 곧 재생 중지입니다.
  // 크기는 카드가 정합니다. 가로형은 860 안의 16:9, 숏츠는 반 폭의 9:16 그대로 플레이어가
  // 됩니다. 눌린 자리에서 커지지 않으므로 글 읽던 위치도 밀리지 않습니다.
  document.addEventListener('click', function (e) {
    var a = e.target && e.target.closest && e.target.closest('.izv'), b, id;
    if (!a) return;
    e.preventDefault();
    b = a.querySelector('.izv-b');
    id = a.parentNode.getAttribute('data-izv');
    if (!b || !id || b.querySelector('iframe')) return;   // 재생 중인 카드를 또 누른 것
    stop();
    b.className = 'izv-b on';
    b.insertAdjacentHTML('beforeend', '<iframe allowfullscreen allow="autoplay; encrypted-media" src="https://www.youtube.com/embed/' +
      id + '?autoplay=1&playsinline=1&rel=0"></iframe>');
  }, true);
  // 새 영상을 누르면 먼저 틀어 둔 것을 썸네일로 되돌립니다. 소리가 겹치지 않게 하려는 것이고,
  // 한 화면에 재생 중인 플레이어가 둘 이상 서 있지 않게 하려는 것이기도 합니다.
  function stop() {
    [].forEach.call(Q('.izv-b.on'), function (b) {
      var f = b.querySelector('iframe');
      if (f) b.removeChild(f);
      b.className = 'izv-b';
    });
  }
  // 상세설명은 큐샵이 나중에 그려 넣으므로 한 번만 훑으면 놓칩니다. 변경을 다음 프레임
  // 한 번으로 모아서 처리합니다.
  var q = 0;
  function go() {
    if (q) return;
    q = 1;
    (window.requestAnimationFrame || function (f) { setTimeout(f, 16); })(function () { q = 0; scan(); });
  }
  go();
  try { new MutationObserver(go).observe(document.documentElement, { childList: 1, subtree: 1 }); } catch (e) {}
})();

/* ===== itzip-6-cta.js ===== */
(function () {
  // 현장 상세설명 본문에 방문예약 폼(또는 배너)을 끼워 넣습니다.
  //
  // 왜 공통코드에서 하나: 상세설명 에디터는 저장할 때 직접 넣은 div/a/style/script 를 전부
  // 지웁니다. 남는 것은 이미지, 표, 문단(글), HTML 주석뿐입니다. 그래서 유튜브 카드와 같은
  // 방식으로, 에디터에는 표시만 남기고 실제 내용은 여기서 그립니다.
  //
  // 상세설명에 쓰는 표시 (대괄호와 앞뒤 공백은 있으나 없으나 같습니다)
  //   아무것도 안 씀   첫 번째 이미지 바로 밑에 방문예약 폼. 지금 기본값입니다.
  //   [예약폼]         그 자리에 방문예약 폼. 위치를 옮기려면 이 줄을 옮기면 됩니다.
  //   [예약배너]       폼 대신 누르면 팝업이 열리는 배너.
  //   [예약폼없음]     이 현장만 아무것도 넣지 않음.
  //   주석으로 넣어도 같습니다.  <!--예약폼-->
  //
  // 폼은 itzip-3-reserve.js 의 window.fitReserve(자리) 가 그립니다. 팝업으로 열리는 그 폼과
  // 글자 하나까지 같은 것이고, 제출 경로(숨김 iframe 대리 제출 + 웹훅)도 같습니다.
  // 배너 모양은 itzip-6-cta.css, 폼 모양은 itzip-3-reserve.css 가 정합니다.
  if (window.fitCtaUp) return;        // 공통푸터는 페이지당 두 벌 실행됩니다
  window.fitCtaUp = 1;
  var F = '예약폼', B = '예약배너', OFF = '없음';

  // 글자는 전부 우리가 쓴 것이라 innerHTML 로 한 번에 넣습니다. 바깥에서 온 문자열은
  // 하나도 섞이지 않습니다.
  function mkBanner() {
    var a = document.createElement('a');
    a.className = 'izcta';
    a.href = '#';
    a.innerHTML = '<div><b>방문예약 신청하기</b>'
      + '<em>날짜와 시간만 남기시면 담당자가 연락드립니다</em></div>'
      + '<i>예약하기 ›</i>';
    a.onclick = function (e) { e.preventDefault(); if (window.fitReserve) window.fitReserve(); };
    return a;
  }

  // 표시가 문단 안에 들어 있어도 폼은 문단 사이에 통째로 놓이도록, .ck-content 의
  // 직계 자식까지 올라갑니다.
  function up(n, c) { while (n && n.parentNode && n.parentNode !== c) n = n.parentNode; return n; }

  function place() {
    var c = document.querySelector('.productDetailPage #detail .ck-content');
    if (!c || c.querySelector('.izcta,.vr-form')) return;
    var at = null, txt = '', kid = c.children, i, n;
    // 1) 글로 써넣은 표시
    for (i = 0; i < kid.length; i++) {
      txt = (kid[i].textContent || '').replace(/[\s\[\]]/g, '');
      if (txt.indexOf(F) === 0 || txt.indexOf(B) === 0) { at = kid[i]; break; }
      txt = '';
    }
    // 2) 주석으로 넣은 표시. 128 은 주석 노드만 보라는 뜻입니다.
    if (!at) {
      var w = document.createTreeWalker(c, 128);
      while ((n = w.nextNode())) {
        if (n.nodeValue.indexOf(F) >= 0 || n.nodeValue.indexOf(B) >= 0) { txt = n.nodeValue; at = up(n, c); break; }
      }
    }
    if (txt && txt.indexOf(OFF) >= 0) return;        // 이 현장은 넣지 않음
    var form = !txt || txt.indexOf(B) < 0;           // 표시가 없거나 [예약폼] 이면 폼
    // 예약 조각은 이 조각보다 뒤에 있습니다. 아직 안 읽혔으면 다음 기회에 다시 옵니다.
    if (form && !window.fitReserve) { setTimeout(go, 300); return; }
    var el = form ? document.createElement('div') : mkBanner();
    if (txt) {
      at.parentNode.insertBefore(el, at);
      if (at.nodeType == 1) at.parentNode.removeChild(at);   // 글로 쓴 표시는 폼으로 대체
    } else {
      // 3) 표시가 없으면 첫 이미지 다음
      n = c.querySelector('img');
      if (!n) return;
      at = up(n, c).nextSibling;
      if (at) at.parentNode.insertBefore(el, at);
      else c.appendChild(el);
    }
    if (form) window.fitReserve(el);
  }

  // 상세설명은 큐샵이 나중에 그려 넣고 화면을 옮길 때 다시 그리므로, 한 번만 훑으면
  // 놓칩니다. 변경을 다음 프레임 한 번으로 모아서 처리합니다. 우리가 넣은 폼 때문에
  // 다시 불려도 위의 첫 줄 검사에서 바로 돌아섭니다.
  var q = 0;
  function go() {
    if (q) return;
    q = 1;
    (window.requestAnimationFrame || function (f) { setTimeout(f, 16); })(function () { q = 0; place(); });
  }
  go();
  try { new MutationObserver(go).observe(document.documentElement, { childList: 1, subtree: 1 }); } catch (e) {}
})();

/* ===== itzip-3-reserve.js ===== */
// 방문예약 폼. 부르는 법 두 가지입니다.
//   window.fitReserve()       화면을 덮는 팝업으로 엽니다. 상단/하단 CTA 버튼이 이렇게 부릅니다.
//   window.fitReserve(자리)   그 요소 안에 같은 폼을 그대로 그립니다. 상세설명의 [예약폼]
//                             표시를 보고 itzip-6-cta.js 가 이렇게 부릅니다.
// 다른 것은 껍데기뿐입니다. 마크업, 검증, 숨김 iframe 대리 제출, 웹훅까지 전부 같은 코드를
// 지나갑니다. 모양은 itzip-3-reserve.css 의 .vr-form / #vr-modal / .vr-inline 이 정합니다.
window.fitReserve = function (mount) {
  var RESERVATION_URL = (window.FIT_BRAND || {}).contactPath || '/contact';
  var LBL = '방문예약등록';   // 방문예약등록 - 버튼 글자, 두 군데서 씀

  function currentSite(){ var h = document.querySelector('.productDetailPage h1'); return h ? (h.textContent || '').trim() : ''; }

  function setReactValue(el, value) {
    if (!el) return;
    var proto = el.tagName === 'SELECT' ? window.HTMLSelectElement.prototype : window.HTMLInputElement.prototype;
    var setter = Object.getOwnPropertyDescriptor(proto, 'value').set;
    setter.call(el, value);
    el.dispatchEvent(new Event('input', { bubbles: true }));
    el.dispatchEvent(new Event('change', { bubbles: true }));
    el.dispatchEvent(new Event('blur', { bubbles: true }));
  }

  function findFields(d) {
    var fields = { name: null, phone: null, date: null, time: null, agree: null, site: null, submit: null };
    d.querySelectorAll('[class*="formColumn"], [class*="formGroup"], [class*="FormColumn"]').forEach(function (col) {
      var labelEl = col.querySelector('[class*="formName"]') || col.querySelector('[data-font-preset="Header3"]');
      if (!labelEl) return;
      var label = (labelEl.textContent || '').trim();
      var input = col.querySelector('input, select, textarea');
      if (!input) return;
      if (/^(성함|이름|성명)$/.test(label)) fields.name = input;
      else if (/(연락|전화|휴대|핸드폰)/.test(label)) {
        var psel = col.querySelector('select'), ptx = col.querySelectorAll('input[type="text"]');
        if (psel && ptx.length >= 2) { fields.phoneSel = psel; fields.phoneMid = ptx[0]; fields.phoneLast = ptx[1]; fields.phone = psel; }
        else fields.phone = input;
      }
      else if (/(날짜|일자)/.test(label)) fields.date = input;
      else if (/시간/.test(label)) fields.time = col.querySelector('select') || input;
      else if (/(동의|약관|개인정보)/.test(label)) fields.agree = col.querySelector('input[type="checkbox"]');
      else if (/(현장|단지|물건|캠페인)/.test(label)) fields.site = input;
    });
    fields.submit = d.querySelector('[formid]:not(iframe)') || d.querySelector('[class*="formSubmit"]');
    return fields;
  }

  function ensureHidden(){
    var h = document.getElementById('vr-hidden-frame');
    if (h) return h;
    h = document.createElement('iframe');
    h.id = 'vr-hidden-frame';
    h.style.cssText = 'position:fixed;top:0;left:0;width:1px;height:1px;border:0;opacity:0;pointer-events:none;z-index:-1';
    h.src = RESERVATION_URL;
    document.body.appendChild(h);
    return h;
  }
  function rmHidden(){
    var h = document.getElementById('vr-hidden-frame');
    if (h && h.parentNode) h.parentNode.removeChild(h);   // 다음 제출은 새 iframe 으로
  }

  // 빈 폼으로 되돌립니다. 팝업을 다시 열 때와, 본문에 박힌 폼이 접수를 마쳤을 때 씁니다.
  function clear(box){
    var b = box.querySelector('.vr-submit');
    if (b) { b.disabled = false; b.textContent = LBL; }
    ['vr-name', 'vr-phone-mid', 'vr-phone-last', 'vr-date'].forEach(function (id) { var el = box.querySelector('#' + id); if (el) el.value = ''; });
    var s = box.querySelector('#vr-phone-sel'); if (s) s.value = '010';
    var a = box.querySelector('#vr-agree'); if (a) a.checked = false;
  }

  var wait = function (ms) { return new Promise(function (r) { setTimeout(r, ms); }); };

  // 팝업은 페이지당 하나만 만들고 두 번째부터는 다시 보여 주기만 합니다.
  // 본문에 박는 폼은 부른 자리마다 새로 그리므로 이 길로 오지 않습니다.
  if (!mount) {
    var existing = document.getElementById('vr-modal');
    if (existing) {
      existing.style.display = 'flex';
      document.body.style.overflow = 'hidden';
      clear(existing);
      ensureHidden();
      return;
    }
  }

  var PRIVACY_TEXT = `■ 개인정보 수집, 이용, 위탁, 양도 동의

㈜핏톡은 고객님의 원활한 서비스 이용을 위해 필요한 최소한의 개인정보를 수집하고 있습니다.

- 개인정보 제공받는 자 : ㈜핏톡
- ㈜핏톡은 고객님의 개인정보를 수집하거나 분양상담에 직접 관여하지 않습니다. 제공되는 부동산 정보는 각 콘텐츠 제공업체로부터 받는 정보로 참고용입니다. 정보의 정확성이나 신뢰성을 보증하지 않으며, 서비스 이용의 결과에 대해서 어떠한 법적인 책임을 지지 않습니다.
- 고객님은 개인정보 수집에 동의하지 않을 권리가 있습니다. 다만, 필수 항목에 대한 동의를 거부하실 경우 방문예약 등록이 불가능합니다.

1. 수집하는 개인정보 항목
- 필수 항목 : 이름, 휴대전화번호, 방문일자, 방문시간

2. 개인정보의 수집 및 이용 목적
- 이름, 휴대전화번호 : 분양 정보 안내, 상담, 고지사항 전달, 불만 처리, 이벤트 정보 제공

3. 개인정보의 보유 및 이용 기간
수집된 개인정보는 원칙적으로 방문예약 등록 시점부터 분양 완료 시까지 보유 및 이용합니다. 단, 마케팅 활용 동의 시에는 별도의 보유 기간을 따릅니다.

- 파기 절차: 분양 완료 후 별도 DB로 이관하여 일정 기간 보관 후 파기
- 파기 방법: 전자적 파일 형태의 정보는 복구 불가능한 기술적 방법을 사용하여 영구 삭제하며, 종이 문서 형태의 정보는 분쇄하거나 소각합니다.`;

  // 큐샵 예약 폼의 앞자리 select 와 같은 목록, 같은 순서입니다.
  var PHONE_PREFIXES = ['010','02','031','032','033','041','042','043','044',
                        '051','052','053','054','055','061','062','063','064','070'];
  var phoneOptions = PHONE_PREFIXES.map(function (p) {
    return '<option value="' + p + '">' + p + '</option>';
  }).join('');

  var timeOptions = '';
  for (var hnum = 10; hnum <= 18; hnum++) {
    var hh = hnum < 10 ? '0' + hnum : hnum;
    timeOptions += '<option value="' + hh + ':00">' + hh + ':00</option>';
    if (hnum < 18) timeOptions += '<option value="' + hh + ':30">' + hh + ':30</option>';
  }

  // .vr-row 는 폼이 넓을 때(본문 860) 한 줄에 두 칸씩 세우려고 묶어 둔 것입니다.
  // 좁을 때는 그냥 div 라서 예전처럼 한 줄에 한 칸씩 쌓입니다. 가르는 것은
  // itzip-3-reserve.css 의 컨테이너 쿼리 하나뿐이고 여기 JS 는 몰라도 됩니다.
  var root = document.createElement('div');
  root.className = mount ? 'vr-form vr-inline' : 'vr-form';
  if (!mount) root.id = 'vr-modal';
  root.innerHTML = `
<div class="vr-box">
<h2>${LBL}</h2>
<p class="vr-sub">원활하고 빠른 상담을 위해 정보를 남겨주세요.</p>
<div class="vr-row">
<div class="vr-field"><div class="vr-label">이름</div><input type="text" id="vr-name" placeholder="이름입력" autocomplete="name"></div>
<div class="vr-field"><div class="vr-label">연락처</div><div class="vr-phone"><select id="vr-phone-sel">${phoneOptions}</select><span class="vr-dash">-</span><input type="tel" id="vr-phone-mid" maxlength="4" inputmode="numeric" autocomplete="off"><span class="vr-dash">-</span><input type="tel" id="vr-phone-last" maxlength="4" inputmode="numeric" autocomplete="off"></div></div>
</div>
<div class="vr-row">
<div class="vr-cell"><div class="vr-field"><div class="vr-label">방문일자</div><input type="date" id="vr-date"></div>
<div class="vr-hint">※날짜 입력을 위해 우측 달력 아이콘을 클릭해 주세요</div></div>
<div class="vr-cell"><div class="vr-field"><div class="vr-label">방문시간</div><select id="vr-time">${timeOptions}</select></div></div>
</div>
<div class="vr-policy-head" id="vr-policy-toggle"><span>개인정보 수집 동의 <span style="color:#e53935">*</span></span>
<svg class="vr-arrow" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 9l6 6 6-6"/></svg></div>
<div class="vr-policy" id="vr-policy">${PRIVACY_TEXT}</div>
<label class="vr-agree"><input type="checkbox" id="vr-agree"><span>동의합니다. <strong>[필수]</strong></span></label>
<div class="vr-actions"><button type="button" class="vr-btn vr-submit">${LBL}</button><button type="button" class="vr-btn vr-cancel">닫기</button></div>
</div>`;
  (mount || document.body).appendChild(root);
  if (mount) {
    // 본문에 박힌 폼은 페이지와 함께 처음부터 떠 있습니다. 그래서 숨김 iframe(연락처 페이지)
    // 을 여기서 바로 띄우지 않고, 방문자가 폼에 처음 손을 댈 때 띄웁니다. 폼을 쓰지 않고
    // 지나가는 사람에게 페이지를 한 장 더 받게 할 이유가 없습니다.
    // 두 가지를 다 봅니다. 손가락이나 마우스가 닿는 순간(pointerdown)과 칸에 들어가는
    // 순간(focusin). 어느 쪽이 먼저든 ensureHidden 은 이미 있으면 그냥 돌아섭니다.
    ['pointerdown', 'focusin'].forEach(function (t) { root.addEventListener(t, ensureHidden); });
  } else {
    document.body.style.overflow = 'hidden';
    ensureHidden();
  }

  root.querySelector('#vr-date').min = new Date().toISOString().split('T')[0];
  var phSel  = root.querySelector('#vr-phone-sel');
  var phMid  = root.querySelector('#vr-phone-mid');
  var phLast = root.querySelector('#vr-phone-last');
  // 숫자만. 가운데 칸이 차면 끝 칸으로 넘어가고, 빈 끝 칸에서 백스페이스면 되돌아갑니다.
  [phMid, phLast].forEach(function (el) {
    el.addEventListener('input', function () {
      this.value = this.value.replace(/[^0-9]/g, '').slice(0, 4);
      if (this === phMid && this.value.length === 4) phLast.focus();
    });
  });
  phLast.addEventListener('keydown', function (e) {
    if (e.key === 'Backspace' && this.value === '') { phMid.focus(); }
  });
  // 어느 칸에 번호를 통째로 붙여넣어도 세 칸이 채워집니다.
  [phMid, phLast].forEach(function (el) {
    el.addEventListener('paste', function (e) {
      var txt = (e.clipboardData || window.clipboardData);
      if (!txt) return;
      var d = (txt.getData('text') || '').replace(/[^0-9]/g, '');
      if (d.length < 9) return;                       // 짧게 붙여넣은 것은 위 input 처리에 맡깁니다
      e.preventDefault();
      var pfx = '';
      for (var i = 0; i < PHONE_PREFIXES.length; i++) {
        var p = PHONE_PREFIXES[i];
        if (d.indexOf(p) === 0 && p.length > pfx.length) pfx = p;   // 긴 쪽이 이깁니다 (02 보다 010)
      }
      if (!pfx) return;
      phSel.value = pfx;
      var rest = d.slice(pfx.length);
      phMid.value = rest.slice(0, rest.length - 4).slice(0, 4);
      phLast.value = rest.slice(-4);
      phLast.focus();
    });
  });
  root.querySelector('#vr-policy-toggle').addEventListener('click', function () {
    this.classList.toggle('open');
    root.querySelector('#vr-policy').classList.toggle('show');
  });

  function close() {
    root.style.display = 'none';
    document.body.style.overflow = '';
    rmHidden();
  }
  // 닫기, 바깥 클릭, ESC 는 팝업에만 있습니다. 본문에 박힌 폼은 닫을 것이 없습니다.
  if (!mount) {
    root.querySelector('.vr-cancel').addEventListener('click', close);
    root.addEventListener('click', function (e) { if (e.target === root) close(); });
    document.addEventListener('keydown', function (e) { if (e.key === 'Escape' && document.getElementById('vr-modal') && root.style.display !== 'none') close(); });
  }

  root.querySelector('.vr-submit').addEventListener('click', async function () {
    var name = root.querySelector('#vr-name').value.trim();
    var phonePfx  = phSel.value;
    var phoneMid  = phMid.value.replace(/[^0-9]/g, '');
    var phoneLast = phLast.value.replace(/[^0-9]/g, '');
    var phone     = phonePfx + phoneMid + phoneLast;   // 숫자만. 폼과 웹훅에 그대로 들어갑니다
    var date = root.querySelector('#vr-date').value;
    var time = root.querySelector('#vr-time').value;
    var agree = root.querySelector('#vr-agree').checked;

    if (!name) return alert('이름을 입력해주세요.');
    if (phoneMid.length < 3 || phoneLast.length < 4) return alert('연락처를 정확히 입력해주세요.');
    if (!date) return alert('방문일자를 선택해주세요.');
    if (!agree) return alert('개인정보 수집·이용방침에 동의해주세요.');

    var btn = this;
    var labelText = btn.textContent;
    btn.disabled = true;
    btn.textContent = '처리 중...';

    var h = ensureHidden();
    var f = null, waited = 0;
    while (waited < 20000) {
      await wait(200); waited += 200;
      var d = null; try { d = h.contentDocument; } catch (e) {}
      if (d && d.body) { var ff = findFields(d); if (ff.name && ff.phone && ff.submit) { f = ff; break; } }
    }
    if (!f) {
      alert('네트워크 상태가 좋지 않습니다. 잠시 후 다시 시도해주세요.');
      btn.disabled = false; btn.textContent = labelText;
      return;
    }

    try {
      var d = h.contentDocument;
      try { d.defaultView.alert = function () {}; } catch (e) {}
      setReactValue(f.name, name);
      if (f.phoneSel && f.phoneMid && f.phoneLast) {
        setReactValue(f.phoneSel, phonePfx);      // 우리 select 가 큐샵 것과 같은 목록이라 1:1 로 맞습니다
        setReactValue(f.phoneMid, phoneMid);
        setReactValue(f.phoneLast, phoneLast);
      } else {
        setReactValue(f.phone, phone);
      }
      if (f.date) setReactValue(f.date, date);
      if (f.time) setReactValue(f.time, time);
      if (f.site) setReactValue(f.site, currentSite());
      if (f.agree && !f.agree.checked) f.agree.click();

      await wait(500);
      f.submit.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true, view: d.defaultView }));

      function nameNow(){
        var dd = null; try { dd = h.contentDocument; } catch (e) { return null; }
        if (!dd) return null;
        var el = null;
        dd.querySelectorAll('[class*="formColumn"], [class*="formGroup"]').forEach(function (col) {
          var l = col.querySelector('[class*="formName"]');
          if (l && /^(성함|이름|성명)$/.test((l.textContent || '').trim())) el = col.querySelector('input');
        });
        return el;
      }
      var ok = false, w2 = 0;
      while (w2 < 9000) {
        await wait(200); w2 += 200;
        var nm = nameNow();
        if (nm && nm.value === '') { ok = true; break; }
      }
      if (ok) {
        // 웹훅에는 하이픈 넣은 번호로, phone_raw 에는 숫자만
        var phoneFmt = phonePfx + '-' + phoneMid + '-' + phoneLast;
        var S = window.FIT_SITE || {};
        try { window.fitSendReservation && window.fitSendReservation({
          name:       name,
          phone:      phoneFmt,
          phone_raw:  phone,
          date:       date,
          time:       time,
          site:       (S.name ? S.name() : currentSite()),   // 시트 조회 키
          site_phone:    (S.tel ? S.tel() : ''),                     // 대표번호
          manager_phone: (S.managerPhone ? S.managerPhone() : ''),   // 휴대폰 번호, 문자는 여기로
          page_url:      (S.url ? S.url() : location.href),          // 광고 파라미터까지 붙은 전체 주소
          tel_source:    (S.telSource ? S.telSource() : '')          // table 또는 none
        }); } catch(e){}
        alert('방문예약이 정상적으로 접수되었습니다.\n빠른 시일 내 연락드리겠습니다.');
        btn.disabled = false; btn.textContent = labelText;   // 다음에 열었을 때 눌리도록
        // 본문에 박힌 폼은 닫지 않고 빈 폼으로 되돌립니다.
        if (mount) { clear(root); rmHidden(); } else close();
      } else {
        alert('접수에 실패했습니다. 입력값을 확인 후 다시 시도해주세요.');
        btn.disabled = false; btn.textContent = labelText;
      }
    } catch (e) {
      alert('처리 중 오류가 발생했습니다. 다시 시도해주세요.');
      btn.disabled = false; btn.textContent = labelText;
    }
  });
};

/* ===== itzip-7-slide.js ===== */
(function () {
  // 상세설명 본문의 한 구간을 좌우로 넘기는 슬라이더로 바꿉니다. 타입(평면도)처럼 이미지가
  // 여러 장 이어지는 곳에 씁니다.
  //
  // 상세설명에 쓰는 표시 (예약폼과 같은 결입니다. 주석으로 넣어도 같습니다)
  //   [슬라이드시작]                     여기부터
  //   [슬라이드시작:59A,59B,74A]         탭에 이 이름들을 씁니다
  //   [슬라이드끝]                       여기까지
  //   <!--슬라이드시작--> <!--슬라이드끝-->
  //
  // 한 페이지에 여러 벌을 넣어도 됩니다. 시작과 끝을 짝지어 순서대로 다 만듭니다. 짝이 안
  // 맞는 표시(끝이 없는 시작, 시작이 없는 끝)는 그냥 무시합니다.
  //
  // 두 표시 사이에 있는 것이 재료입니다. 이미지가 아닌 것(빈 문단 등)은 슬라이더에 안 들어
  // 가고 같이 감춰집니다. 구간을 사람이 정해 주므로 코드가 '어디까지가 한 묶음인가'를
  // 추측하지 않습니다. 나중에 사이에 글 한 줄을 끼워 넣어도 묶음이 깨지지 않습니다.
  //
  // 긴 이미지는 알아서 나눕니다: 타입 이미지는 보통 여러 타입이 세로로 이어 붙은 한 장으로
  // 옵니다. 어느 현장은 12타입이 세 장에 나뉘어 있고 한 장이 7429px 입니다. 타입마다 맨 위에
  // 가로를 꽉 채운 머리사진(타입명이 얹힌 사진)이 오고 평면도는 흰 바탕 가운데에만 그림이
  // 있어 가로가 안 찹니다. 그래서 '가로가 거의 다 찬 줄'이 250px 넘게 이어지는 곳이 곧 한
  // 장의 시작입니다. 머리사진 가운데에 흰 면적 상자가 얹혀 있어 한 번 끊기므로 120px 까지
  // 벌어진 것은 이어진 것으로 봅니다. 캔버스에 폭 32 로 줄여 그린 뒤 읽습니다. 폭을 24 로
  // 하든 96 으로 하든 같은 답이 나왔고 세 장을 합쳐 100ms 안쪽입니다.
  // 나눌 곳을 못 찾으면 그 이미지는 통째로 한 장이 됩니다. 평범한 이미지 여러 장을 넣어도
  // 그대로 한 장씩 슬라이드가 되므로 타입이 아닌 곳에도 그냥 쓸 수 있습니다.
  //
  // 이름은 적으면 탭에 쓰고 안 적으면 번호를 씁니다. 개수가 안 맞아도 번호로 물러설 뿐
  // 슬라이더는 그대로 만듭니다. 표시를 못 찾거나 이미지가 없으면 아무것도 하지 않습니다.
  //
  // 코드가 촘촘한 것은 취향이 아니라 큐샵 공통코드 한도 때문입니다. 주석은 빌드가 걷어냅니다.
  if (window.fitSlideUp) return;      // 공통푸터는 페이지당 두 벌 실행됩니다
  window.fitSlideUp = 1;
  var W = 32, LIGHT = 245, FILL = .95, GAP = 120, MIN = 250, A = '슬라이드시작', B = '슬라이드끝';
  function hit(s, w) {
    // [슬라이드시작:이름,이름] 에서 뒤쪽 이름들만 떼어 냅니다. 대괄호와 공백은 있으나 없으나
    // 같고, 콜론이 없으면 이름이 없는 것입니다.
    var m = new RegExp('\\[?\\s*' + w + '\\s*[:\uFF1A]?([^\\]\\n]*)').exec(s || '');
    return m ? m[1] : null;
  }
  function names(s) {
    var a = (s || '').split(/[,\uFF0C]/), r = [], i, v;
    for (i = 0; i < a.length; i++) { v = a[i].replace(/^[\s\]]+|[\s\]]+$/g, ''); if (v) r.push(v); }
    return r;
  }
  // 본문 맨 위에서 아래로 훑으며 표시를 순서대로 모읍니다. 글로 쓴 것과 주석을 한 줄에 놓고
  // 보아야 여러 벌의 짝을 제대로 지을 수 있어서 한 번에 훑습니다.
  //   k=1 시작표시, k=0 끝표시, at=본문 직계 자식(이 자리에 슬라이더가 들어갑니다)
  function marks(c) {
    var out = [], n, wk, q;
    function put(host, s) {
      var x = hit(s, A);
      if (x !== null) { out.push({ k: 1, at: host, s: x }); return 1; }
      x = hit(s, B);
      if (x !== null) { out.push({ k: 0, at: host }); return 1; }
      return 0;
    }
    for (n = c.firstChild; n; n = n.nextSibling) {
      if (n.nodeType == 8) { put(n, n.nodeValue); continue; }
      if (n.nodeType != 1 || (n.querySelector && n.querySelector('img'))) continue;
      if (put(n, n.textContent)) continue;
      wk = document.createTreeWalker(n, 128);   // 128 은 주석 노드만 보라는 뜻입니다
      while ((q = wk.nextNode())) if (put(n, q.nodeValue)) break;
    }
    return out;
  }
  // 두 표시 사이의 직계 자식들. 표시 자체는 뺍니다. 이미 손을 댄 구간이면 null 을 주어
  // 다시 만들지 않게 합니다. 알아보는 표가 셋입니다.
  //   className 'izs'   이미 만들어 둔 슬라이더가 그 자리에 있다
  //   data-izs          만들면서 감춰 둔 원본이다
  //   __izs             지금 이미지를 읽는 중이다. 아직 아무것도 안 생겼지만 임자가 있다
  // 셋째가 없으면 안 됩니다. 이미지를 읽는 동안 큐샵이 본문을 다시 그리면 그때마다 place()
  // 가 불려서 '아직 아무것도 없네' 하고 같은 구간을 또 만들기 시작합니다. 그렇게 출발한
  // 여러 벌이 나중에 다 같이 완성되어 슬라이더가 서너 개씩 겹쳐 쌓입니다.
  // 자바스크립트 속성으로 두는 이유는, 만들다 실패했을 때 아래 place() 의 '되살아난 원본
  // 다시 감추기'가 이 노드들까지 감춰서 이미지를 통째로 없애 버리면 안 되기 때문입니다.
  function seg(c, a, b) {
    var r = [], n, on = 0, had = 0;
    for (n = c.firstChild; n; n = n.nextSibling) {
      if (n === a) { on = 1; continue; }
      if (n === b) return had ? null : r;
      if (!on || n.nodeType != 1) continue;
      if (n.className === 'izs' || n.__izs || n.getAttribute('data-izs')) { had = 1; continue; }
      r.push(n);
    }
    return null;                                 // 끝 표시가 시작보다 앞에 있으면 포기합니다
  }
  // 픽셀을 읽으려면 CORS 로 받아 둔 그림이어야 합니다. 아직 아니면 모드를 바꿔 다시 물립니다.
  // 슬라이드가 쓸 img 도 같은 주소에 같은 모드라 브라우저가 받아 둔 것을 그대로 씁니다.
  // 그래서 12장이 원본 세 장을 나눠 써도 내려받는 것은 결국 세 장뿐입니다.
  function ready(im, cb) {
    if (im.crossOrigin && im.complete && im.naturalWidth) return cb(im);
    function off() { im.removeEventListener('load', on); im.removeEventListener('error', er); }
    function on() { off(); cb(im.naturalWidth ? im : null); }
    function er() { off(); cb(null); }
    im.addEventListener('load', on);
    im.addEventListener('error', er);
    if (!im.crossOrigin) { var u = im.src; im.crossOrigin = 'anonymous'; im.src = u; }
  }
  // 한 장이 시작하는 y 들. 못 읽으면(그림이 있는 곳이 CORS 를 안 열어 준 경우) 통째로 한 장
  // 으로 봅니다. 나눌 곳을 못 찾았을 때도 마찬가지입니다.
  function cuts(im) {
    var H = im.naturalHeight, c = document.createElement('canvas'), g, d, y, x, i, n, run = [], st = null, m = [], out = [];
    if (!H || !c.getContext) return [0];
    c.width = W; c.height = H;
    g = c.getContext('2d');
    g.drawImage(im, 0, 0, W, H);
    try { d = g.getImageData(0, 0, W, H).data; } catch (e) { return [0]; }
    for (y = 0; y < H; y++) {
      n = 0;
      for (x = 0; x < W; x++) {
        i = (y * W + x) * 4;
        if ((d[i] * 299 + d[i + 1] * 587 + d[i + 2] * 114) / 1000 < LIGHT) n++;
      }
      if (n / W > FILL) { if (st === null) st = y; }
      else if (st !== null) { run.push([st, y]); st = null; }
    }
    if (st !== null) run.push([st, H]);
    for (i = 0; i < run.length; i++) {
      if (m.length && run[i][0] - m[m.length - 1][1] < GAP) m[m.length - 1][1] = run[i][1];
      else m.push([run[i][0], run[i][1]]);
    }
    for (i = 0; i < m.length; i++) if (m[i][1] - m[i][0] >= MIN) out.push(m[i][0]);
    if (!out.length || out[0] !== 0) out.unshift(0);   // 첫 장은 언제나 맨 위에서 시작합니다
    return out;
  }
  // 이름은 에디터에서 온 남의 글자라 textContent 로만 넣습니다. 주소는 이미 페이지에 있던
  // 이미지의 것을 src 로 직접 옮깁니다. innerHTML 로 문자열을 이어 붙이지 않습니다.
  function build(nm, rows, list) {
    var b = [], i, im, t, j, box, tabs, view, track, prev, next, cur = 0, bt = [];
    for (i = 0; i < list.length; i++) {
      if (!list[i]) continue;
      im = list[i].im; t = list[i].cuts;
      for (j = 0; j < t.length; j++)
        b.push({ u: im.src, w: im.naturalWidth, h: im.naturalHeight, y: t[j], d: (j + 1 < t.length ? t[j + 1] : im.naturalHeight) - t[j] });
    }
    if (b.length < 2) return 0;                  // 한 장뿐이면 넘길 것이 없습니다
    // 그리기 직전 마지막 확인. 여기까지 오는 길이 비동기라(이미지를 기다립니다) 그 사이에
    // 다른 경로로 이미 만들어졌을 수 있습니다. 이 검사와 위 __izs 임자 표시 둘 다 있어야
    // 같은 자리에 두 벌이 겹쳐 쌓이지 않습니다.
    for (i = 0; i < rows.length; i++) if (!rows[i].parentNode || rows[i].getAttribute('data-izs')) return 0;
    if (nm.length !== b.length) nm = null;       // 개수가 안 맞으면 이름 대신 번호
    box = document.createElement('div'); box.className = 'izs';
    tabs = document.createElement('div'); tabs.className = 'izs-tabs';
    view = document.createElement('div'); view.className = 'izs-view';
    track = document.createElement('div'); track.className = 'izs-track';
    for (i = 0; i < b.length; i++) {
      var s = document.createElement('div'), g = document.createElement('img'), e = document.createElement('button');
      s.className = 'izs-s';
      s.style.paddingBottom = (b[i].d / b[i].w * 100).toFixed(3) + '%';
      g.crossOrigin = 'anonymous';
      g.alt = nm ? nm[i] : '';
      g.style.transform = 'translateY(' + (-b[i].y / b[i].h * 100).toFixed(4) + '%)';
      g.src = b[i].u;
      s.appendChild(g); track.appendChild(s);
      e.type = 'button'; e.textContent = nm ? nm[i] : String(i + 1);
      e.onclick = (function (k) { return function () { go(k); }; })(i);
      tabs.appendChild(e); bt.push(e);
    }
    // 꺾쇠 모양은 css 가 배경 그림으로 넣습니다. 글자로 두면 폰트마다 좌우 여백이 달라
    // 동그라미 한가운데에 안 섭니다.
    prev = document.createElement('b'); prev.className = 'izs-a izs-p';
    next = document.createElement('b'); next.className = 'izs-a izs-n';
    prev.onclick = function () { go(cur - 1); };
    next.onclick = function () { go(cur + 1); };
    view.appendChild(track); view.appendChild(prev); view.appendChild(next);
    box.appendChild(tabs); box.appendChild(view);
    // 끝에서 한 칸 더 가면 처음으로, 처음에서 뒤로 가면 끝으로 돌아옵니다.
    // 두 칸 넘게 건너뛸 때는 애니메이션을 끕니다. 탭으로 59A 에서 125P 로 갈 때 열두 장을
    // 0.3초 만에 훑고 지나가면 그냥 번쩍이는 것으로 보이고, 끝에서 처음으로 도는 것도
    // 되감기처럼 보이기 때문입니다. 옆칸으로 한 칸씩 움직일 때만 미끄러집니다.
    function go(k) {
      var n = b.length, far, i2;
      k = (k % n + n) % n;
      far = Math.abs(k - cur) > 1;
      cur = k;
      if (far) track.style.transition = 'none';
      track.style.transform = 'translateX(' + (-k * 100) + '%)';
      if (far) { void track.offsetWidth; track.style.transition = ''; }   // 리플로우로 즉시 반영
      view.style.paddingBottom = (b[k].d / b[k].w * 100).toFixed(3) + '%';
      for (i2 = 0; i2 < bt.length; i2++) bt[i2].className = i2 === k ? 'on' : '';
      tabs.scrollLeft = bt[k].offsetLeft - (tabs.clientWidth - bt[k].offsetWidth) / 2;
    }
    // 손가락으로 밀기. 처음 몇 px 로 가로인지 세로인지 정하고 가로일 때만 화면 스크롤을
    // 막습니다. 이러지 않으면 슬라이더 위에서 페이지를 위아래로 못 넘깁니다.
    var x0 = 0, y0 = 0, dx = 0, way = 0;
    view.addEventListener('touchstart', function (e) {
      x0 = e.touches[0].clientX; y0 = e.touches[0].clientY; dx = 0; way = 0;
      track.style.transition = 'none';
    }, true);
    function drag(e) {
      var ax = e.touches[0].clientX - x0, ay = e.touches[0].clientY - y0;
      if (!way) way = Math.abs(ax) > Math.abs(ay) + 4 ? 1 : Math.abs(ay) > 4 ? 2 : 0;
      if (way != 1) return;
      dx = ax;
      if (e.cancelable) e.preventDefault();
      track.style.transform = 'translateX(calc(' + (-cur * 100) + '% + ' + Math.round(dx) + 'px))';
    }
    // passive:false 를 줘야 preventDefault 가 먹습니다. 옵션 객체를 모르는 옛 브라우저는
    // 두 번째 인자를 참으로 읽어 캡처로 붙는데 그래도 동작에는 지장이 없습니다.
    try { view.addEventListener('touchmove', drag, { passive: false }); }
    catch (e) { view.addEventListener('touchmove', drag, false); }
    view.addEventListener('touchend', function () {
      track.style.transition = '';
      go(way == 1 && Math.abs(dx) > 40 ? cur + (dx < 0 ? 1 : -1) : cur);
    }, true);
    rows[0].parentNode.insertBefore(box, rows[0]);
    for (i = 0; i < rows.length; i++) { rows[i].setAttribute('data-izs', '1'); gone(rows[i]); }
    go(0);
    return 1;
  }
  // 원본을 감출 때 !important 를 같이 걸어야 합니다. 랜딩 조각이 모바일에서
  //   @media(max-width:768px){ .productDetailPage #detail figure.image{display:block !important} }
  // 를 걸어 두는데, 그냥 인라인 style.display='none' 은 !important 가 아니라서 이 규칙에
  // 집니다. 그러면 PC 에서는 멀쩡한데 휴대폰에서만 슬라이더 아래에 원본 긴 이미지가
  // 그대로 딸려 나옵니다. 인라인에 !important 를 붙이면 어떤 스타일시트보다 세므로
  // 화면 크기와 상관없이 확실히 감춰집니다.
  function gone(n) {
    if (n.style.setProperty) n.style.setProperty('display', 'none', 'important');
    else n.style.display = 'none';
  }
  function place() {
    var c = document.querySelector('.productDetailPage #detail .ck-content'), old, all, i, a = null;
    if (!c) return;
    // 큐샵이 상세설명을 다시 그리면 감춰 둔 원본이 되살아납니다. 그때는 다시 감춥니다.
    old = c.querySelectorAll('[data-izs]');
    for (i = 0; i < old.length; i++) gone(old[i]);
    all = marks(c);
    for (i = 0; i < all.length; i++) {
      if (all[i].k) { a = all[i]; continue; }   // 시작표시를 들고 있다가
      if (!a) continue;                         // 짝 없는 끝표시는 버립니다
      one(c, a, all[i]);
      a = null;
    }
  }
  // 한 벌을 만듭니다. 이미지를 다 읽은 뒤에야 그릴 수 있으므로 여기서 기다립니다.
  function one(c, a, z) {
    var rows = seg(c, a.at, z.at), ims = [], list = [], left, i, e;
    if (!rows || !rows.length) return;
    for (i = 0; i < rows.length; i++) { e = rows[i].querySelector && rows[i].querySelector('img'); if (e) ims.push(e); }
    if (!ims.length) return;
    for (i = 0; i < rows.length; i++) rows[i].__izs = 1;   // 임자 표시. 기다리기 전에 박습니다
    left = ims.length;
    for (i = 0; i < ims.length; i++) grab(i);
    function grab(k) {
      ready(ims[k], function (im) {
        list[k] = im ? { im: im, cuts: cuts(im) } : null;
        if (--left) return;
        if (!build(names(a.s), rows, list)) return;   // 못 만들면 지금 모습 그대로 둡니다
        drop(a.at); drop(z.at);
      });
    }
    // 글로 쓴 표시는 지웁니다. 주석은 어차피 안 보이므로 그대로 둡니다. 다시 훑을 때는
    // seg() 가 이미 만든 구간을 알아보고 건너뜁니다.
    function drop(n) { if (n.nodeType == 1 && n.parentNode) n.parentNode.removeChild(n); }
  }
  // 상세설명은 큐샵이 나중에 그려 넣으므로 한 번만 훑으면 놓칩니다. 변경을 다음 프레임
  // 한 번으로 모아서 처리합니다.
  var q = 0;
  function scan() {
    if (q) return;
    q = 1;
    (window.requestAnimationFrame || function (f) { setTimeout(f, 16); })(function () { q = 0; place(); });
  }
  scan();
  try { new MutationObserver(scan).observe(document.documentElement, { childList: 1, subtree: 1 }); } catch (e) {}
})();
