/* ItZip platform site - built by build-footers.ps1 from parts\.
   Do not edit this file. Edit parts\*.js and run build-footers.ps1. */

/* ===== itzip-head-1-webhook.js ===== */
// 예약 웹훅. 예약 모달(itzip-3-reserve.js)이 확인 버튼에서 이걸 부릅니다.
//
// 이 조각이 반드시 맨 앞이어야 합니다. 뒤의 itzip-head-5-conversion.js 가
// window.fitSendReservation 를 가로채서 네이버 전환까지 같이 쏘는데, 가로챌 때
// 원본 함수를 붙잡아 두는 방식이라 원본이 먼저 있어야 합니다.
(function () {
  window.FIT_WEBHOOK_URL = 'https://hooks.zapier.com/hooks/catch/27272127/46rfuef/';
  window.fitSendReservation = function (p) {
    try {
      if (!window.FIT_WEBHOOK_URL || !p) return;

      // The 휴대폰 번호 cell on the contact page may name several people, in which case it
      // arrives here comma joined. It goes out three ways so the Zap can use whichever is
      // least work: the joined string, a count, and one numbered field per recipient.
      // With a single recipient manager_phone reads exactly as it always did.
      var recips = String(p.manager_phone || '').split(',');
      var list = [];
      for (var i = 0; i < recips.length; i++) {
        var m = recips[i].replace(/[^0-9-]/g, '');
        if (m) list.push(m);
      }
      function digits(s) { return String(s || '').replace(/[^0-9]/g, ''); }

      var body = 'name='       + encodeURIComponent(p.name || '')
               + '&phone='      + encodeURIComponent(p.phone || '')
               + '&phone_raw='  + encodeURIComponent(digits(p.phone_raw || p.phone))
               + '&date='       + encodeURIComponent(p.date || '')
               + '&time='       + encodeURIComponent(p.time || '')
               + '&site='       + encodeURIComponent(p.site || '')
               + '&site_phone=' + encodeURIComponent(p.site_phone || '')
               + '&manager_phone=' + encodeURIComponent(list.join(','))
               + '&manager_phone_raw=' + encodeURIComponent(list.map(digits).join(','))
               + '&manager_count=' + list.length
               + '&page_url='   + encodeURIComponent(p.page_url || location.href)
               + '&tel_source=' + encodeURIComponent(p.tel_source || '')
               + '&source=modal';

      // manager_phone_1, manager_phone_1_raw, manager_phone_2, ... so the Zap can wire one
      // send step per recipient without a split or a loop.
      for (var j = 0; j < list.length; j++) {
        body += '&manager_phone_' + (j + 1) + '=' + encodeURIComponent(list[j])
              + '&manager_phone_' + (j + 1) + '_raw=' + encodeURIComponent(digits(list[j]));
      }

      fetch(window.FIT_WEBHOOK_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: body,
        keepalive: true,
        mode: 'no-cors'
      });
    } catch (e) {}
  };
})();

/* ===== itzip-head-2-smartlog.js ===== */
// 스마트로그(smlog) 유입 분석. 원래 큐샵 Header 에 <script src> 로 직접 걸려 있었고,
// 여기서는 코드로 붙입니다.
//
// 늦게 붙여도 되는지 확인한 것: smart_renew.js 안에 document.write 가 두 군데 있는데
// 둘 다 document.body || document.write("<body></body>") 꼴입니다. body 가 이미
// 있는 시점에는 실행되지 않으므로 페이지를 날려먹지 않습니다. (2026-08-20 배포본 확인)
//
// hpt_info 는 smart_renew.js 가 읽어가는 전역이라 스크립트보다 먼저 있어야 합니다.
(function () {
  window.hpt_info = { '_account': 'UHPT-300964', '_server': 'a300' };

  var s = document.createElement('script');
  s.type = 'text/javascript';
  s.async = true;
  s.charset = 'utf-8';
  s.src = 'https://cdn.smlog.co.kr/core/smart_renew.js';
  (document.head || document.documentElement).appendChild(s);
})();

/* ===== itzip-head-3-ga4.js ===== */
// GA4. 원래 큐샵 Body 에 있던 표준 gtag 스니펫과 같습니다.
//
// gtag 와 dataLayer 는 window 에 직접 답니다. IIFE 안에서 var 로 선언하면 지역변수가
// 되어 콘솔에서 gtag 를 못 찾습니다.
(function () {
  var ID = 'G-1QRQBCQ7TH';

  window.dataLayer = window.dataLayer || [];
  window.gtag = function () { window.dataLayer.push(arguments); };
  window.gtag('js', new Date());
  window.gtag('config', ID);

  var s = document.createElement('script');
  s.async = true;
  s.src = 'https://www.googletagmanager.com/gtag/js?id=' + ID;
  (document.head || document.documentElement).appendChild(s);
})();

/* ===== itzip-head-4-naver.js ===== */
// 네이버 전환추적 - 로더. 실제 전환을 쏘는 쪽은 itzip-head-5-conversion.js 입니다.
//
// 원래는 wcslog.js 를 막는 <script src> 로 불러온 다음 바로 아래 인라인에서
// wcs_add 를 채우고 wcs.inflow() 를 불렀습니다. 여기서는 스크립트를 코드로 붙이므로
// inflow 를 onload 로 미룹니다. 순서만 같으면 결과는 같습니다.
//
// wcs_add 와 _nasa 는 스크립트를 붙이기 전에 먼저 채웁니다. 원본보다 이른 시점인데,
// 이르면 이를수록 안전하고(wcslog 가 로드 중에 읽더라도 이미 있음) 콘솔 점검을
// 네트워크가 느린 날에도 통과합니다.
(function () {
  window.wcs_add = window.wcs_add || {};
  window.wcs_add['wa'] = 's_4d7836409a97';
  window._nasa = window._nasa || {};

  var s = document.createElement('script');
  s.type = 'text/javascript';
  s.async = true;
  s.src = 'https://wcs.naver.net/wcslog.js';
  s.onload = function () {
    try {
      if (!window.wcs) return;
      window.wcs.inflow();
      window.wcs_do();
    } catch (e) {}
  };
  (document.head || document.documentElement).appendChild(s);
})();

/* ===== itzip-head-5-conversion.js ===== */
// 네이버 전환 발사. 두 가지를 잡습니다.
//   방문예약 완료  -> cnv "2"   (fitSendReservation 가로채기)
//   전화연결 클릭  -> cnv "5"   (tel: 링크와 상담 버튼 mousedown)
//
// iframe 안에서는 통째로 건너뜁니다. 배너나 코드위젯 안에서 한 번 더 세면
// 전환이 부풀기 때문입니다. 원본 Body 코드도 이 세 블록에만 같은 가드를 두었습니다.
// (GA4 와 wcslog 로더에는 가드가 없었고, 그 동작을 그대로 옮겼습니다.)
//
// NA_SEND 를 가로채기보다 먼저 정의합니다. 원본은 순서가 반대였는데, 어느 쪽이든
// 실제로 부르는 시점은 클릭 이후라 결과는 같습니다.
(function () {
  if (window.top !== window.self) return;

  window.NA_SEND = function (type) {
    try {
      if (!window.wcs) return;
      if (!window._nasa) window._nasa = {};
      window._nasa['cnv'] = window.wcs.cnv(type === 'schedule' ? '2' : '5', '1');
      window.wcs_do(window._nasa);
    } catch (e) {}
  };

  // 방문예약 완료.
  //
  // 값을 덮어쓰지 않고 getter 로 감쌉니다. 이렇게 해야 나중에 누가
  // window.fitSendReservation 를 다시 대입해도(setter 가 받아 둡니다) 전환이
  // 계속 붙어 있습니다. 대표님 점검 스크립트도 이 getter 가 있는지로 확인합니다.
  var _inner = window.fitSendReservation;
  try {
    Object.defineProperty(window, 'fitSendReservation', {
      configurable: true,
      get: function () {
        return function () {
          window.NA_SEND('schedule');
          if (typeof _inner === 'function') {
            try { return _inner.apply(this, arguments); } catch (e) {}
          }
        };
      },
      set: function (fn) { _inner = fn; }
    });
  } catch (e) {
    // defineProperty 가 막힌 브라우저용. 원본은 여기서 웹훅을 버리고 전환만 쐈는데,
    // 그러면 예약이 자피어로 안 갑니다. 둘 다 부르도록 고쳤습니다.
    var _orig = _inner;
    window.fitSendReservation = function () {
      window.NA_SEND('schedule');
      if (typeof _orig === 'function') {
        try { return _orig.apply(this, arguments); } catch (e2) {}
      }
    };
  }

  // 전화연결 클릭. 캡처 단계라 다른 코드가 클릭을 삼켜도 잡힙니다.
  // 같은 클릭이 여러 요소를 타고 두 번 세지지 않게 3초 안에는 한 번만 셉니다.
  var lastCall = 0;
  document.addEventListener('mousedown', function (e) {
    var t = e.target;
    if (!t || !t.closest) return;
    if (!t.closest('a.fit-consult, [data-fit-cta], a[href^="tel:"]')) return;
    var now = Date.now();
    if (now - lastCall < 3000) return;
    lastCall = now;
    window.NA_SEND('custom001');
  }, true);
})();
