/* ItZip platform site - built by build-footers.ps1 from parts\.
   Do not edit this file. Edit parts\*.js and run build-footers.ps1. */

/* ===== itzip-head-1-webhook.js ===== */
// 예약 웹훅. 예약 모달(itzip-3-reserve.js)이 확인 버튼에서 이걸 부릅니다.
//
// 이 조각이 반드시 맨 앞이어야 합니다. 뒤의 itzip-head-5-conversion.js 가
// window.fitSendReservation 를 가로채서 네이버 전환까지 같이 쏘는데, 가로챌 때
// 원본 함수를 붙잡아 두는 방식이라 원본이 먼저 있어야 합니다.
(function () {
  window.FIT_WEBHOOK_URL = 'https://hooks.zapier.com/hooks/catch/27272127/46rfuef/';
  window.fitSendReservation = function (p) {
    try {
      if (!window.FIT_WEBHOOK_URL || !p) return;

      // The 휴대폰 번호 cell on the contact page may name several people, in which case it
      // arrives here comma joined. It goes out three ways so the Zap can use whichever is
      // least work: the joined string, a count, and one numbered field per recipient.
      // With a single recipient manager_phone reads exactly as it always did.
      var recips = String(p.manager_phone || '').split(',');
      var list = [];
      for (var i = 0; i < recips.length; i++) {
        var m = recips[i].replace(/[^0-9-]/g, '');
        if (m) list.push(m);
      }
      function digits(s) { return String(s || '').replace(/[^0-9]/g, ''); }

      var body = 'name='       + encodeURIComponent(p.name || '')
               + '&phone='      + encodeURIComponent(p.phone || '')
               + '&phone_raw='  + encodeURIComponent(digits(p.phone_raw || p.phone))
               + '&date='       + encodeURIComponent(p.date || '')
               + '&time='       + encodeURIComponent(p.time || '')
               + '&site='       + encodeURIComponent(p.site || '')
               + '&site_phone=' + encodeURIComponent(p.site_phone || '')
               + '&manager_phone=' + encodeURIComponent(list.join(','))
               + '&manager_phone_raw=' + encodeURIComponent(list.map(digits).join(','))
               + '&manager_count=' + list.length
               + '&page_url='   + encodeURIComponent(p.page_url || location.href)
               + '&tel_source=' + encodeURIComponent(p.tel_source || '')
               + '&source=modal';

      // manager_phone_1, manager_phone_1_raw, manager_phone_2, ... so the Zap can wire one
      // send step per recipient without a split or a loop.
      for (var j = 0; j < list.length; j++) {
        body += '&manager_phone_' + (j + 1) + '=' + encodeURIComponent(list[j])
              + '&manager_phone_' + (j + 1) + '_raw=' + encodeURIComponent(digits(list[j]));
      }

      fetch(window.FIT_WEBHOOK_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: body,
        keepalive: true,
        mode: 'no-cors'
      });
    } catch (e) {}
  };
})();

/* ===== itzip-head-2-smartlog.js ===== */
// 스마트로그(smlog) 유입 분석. 원래 큐샵 Header 에 <script src> 로 직접 걸려 있었고,
// 여기서는 코드로 붙입니다.
//
// 늦게 붙여도 되는지 확인한 것: smart_renew.js 안에 document.write 가 두 군데 있는데
// 둘 다 document.body || document.write("<body></body>") 꼴입니다. body 가 이미
// 있는 시점에는 실행되지 않으므로 페이지를 날려먹지 않습니다. (2026-08-20 배포본 확인)
//
// hpt_info 는 smart_renew.js 가 읽어가는 전역이라 스크립트보다 먼저 있어야 합니다.
(function () {
  window.hpt_info = { '_account': 'UHPT-300964', '_server': 'a300' };

  var s = document.createElement('script');
  s.type = 'text/javascript';
  s.async = true;
  s.charset = 'utf-8';
  s.src = 'https://cdn.smlog.co.kr/core/smart_renew.js';
  (document.head || document.documentElement).appendChild(s);
})();

/* ===== itzip-head-3-ga4.js ===== */
// GA4. 원래 큐샵 Body 에 있던 표준 gtag 스니펫과 같습니다.
//
// gtag 와 dataLayer 는 window 에 직접 답니다. IIFE 안에서 var 로 선언하면 지역변수가
// 되어 콘솔에서 gtag 를 못 찾습니다.
(function () {
  var ID = 'G-1QRQBCQ7TH';

  window.dataLayer = window.dataLayer || [];
  window.gtag = function () { window.dataLayer.push(arguments); };
  window.gtag('js', new Date());
  window.gtag('config', ID);

  var s = document.createElement('script');
  s.async = true;
  s.src = 'https://www.googletagmanager.com/gtag/js?id=' + ID;
  (document.head || document.documentElement).appendChild(s);
})();

/* ===== itzip-head-4-naver.js ===== */
// 네이버 전환추적 - 로더. 실제 전환을 쏘는 쪽은 itzip-head-5-conversion.js 입니다.
//
// 원래는 wcslog.js 를 막는 <script src> 로 불러온 다음 바로 아래 인라인에서
// wcs_add 를 채우고 wcs.inflow() 를 불렀습니다. 여기서는 스크립트를 코드로 붙이므로
// inflow 를 onload 로 미룹니다. 순서만 같으면 결과는 같습니다.
//
// wcs_add 와 _nasa 는 스크립트를 붙이기 전에 먼저 채웁니다. 원본보다 이른 시점인데,
// 이르면 이를수록 안전하고(wcslog 가 로드 중에 읽더라도 이미 있음) 콘솔 점검을
// 네트워크가 느린 날에도 통과합니다.
/* ===== itzip-head-4-naver.js ===== */
(function () {
  window.wcs_add = window.wcs_add || {};
  window.wcs_add['wa'] = 's_4d7836409a97';
  window._nasa = window._nasa || {};

  var s = document.createElement('script');
  s.type = 'text/javascript';
  s.async = true;
  s.src = 'https://wcs.naver.net/wcslog.js';
  s.onload = function () {
    try {
      if (!window.wcs) return;
      window.wcs.inflow();
      window.wcs_do();
    } catch (e) {}
  };
  (document.head || document.documentElement).appendChild(s);
})();

/* ===== itzip-head-5-conversion.js ===== */
// 네이버 전환 발사. 두 가지를 잡습니다.
//   방문예약 완료  -> cnv "2"   (fitSendReservation 가로채기)
//   전화연결 클릭  -> cnv "5"   (tel: 링크와 상담 버튼 mousedown)
//
// iframe 안에서는 통째로 건너뜁니다. 배너나 코드위젯 안에서 한 번 더 세면
// 전환이 부풀기 때문입니다. 원본 Body 코드도 이 세 블록에만 같은 가드를 두었습니다.
// (GA4 와 wcslog 로더에는 가드가 없었고, 그 동작을 그대로 옮겼습니다.)
//
// NA_SEND 를 가로채기보다 먼저 정의합니다. 원본은 순서가 반대였는데, 어느 쪽이든
// 실제로 부르는 시점은 클릭 이후라 결과는 같습니다.
(function () {
  if (window.top !== window.self) return;

  window.NA_SEND = function (type) {
    try {
      if (!window.wcs) return;
      if (!window._nasa) window._nasa = {};
      window._nasa['cnv'] = window.wcs.cnv(type === 'schedule' ? '2' : '5', '1');
      window.wcs_do(window._nasa);
    } catch (e) {}
  };

  // 방문예약 완료.
  //
  // 값을 덮어쓰지 않고 getter 로 감쌉니다. 이렇게 해야 나중에 누가
  // window.fitSendReservation 를 다시 대입해도(setter 가 받아 둡니다) 전환이
  // 계속 붙어 있습니다. 대표님 점검 스크립트도 이 getter 가 있는지로 확인합니다.
  var _inner = window.fitSendReservation;
  try {
    Object.defineProperty(window, 'fitSendReservation', {
      configurable: true,
      get: function () {
        return function () {
          window.NA_SEND('schedule');
          if (typeof _inner === 'function') {
            try { return _inner.apply(this, arguments); } catch (e) {}
          }
        };
      },
      set: function (fn) { _inner = fn; }
    });
  } catch (e) {
    // defineProperty 가 막힌 브라우저용. 원본은 여기서 웹훅을 버리고 전환만 쐈는데,
    // 그러면 예약이 자피어로 안 갑니다. 둘 다 부르도록 고쳤습니다.
    var _orig = _inner;
    window.fitSendReservation = function () {
      window.NA_SEND('schedule');
      if (typeof _orig === 'function') {
        try { return _orig.apply(this, arguments); } catch (e2) {}
      }
    };
  }

  // 전화연결 클릭. 캡처 단계라 다른 코드가 클릭을 삼켜도 잡힙니다.
  // 같은 클릭이 여러 요소를 타고 두 번 세지지 않게 3초 안에는 한 번만 셉니다.
  var lastCall = 0;
  document.addEventListener('mousedown', function (e) {
    var t = e.target;
    if (!t || !t.closest) return;
    if (!t.closest('a.fit-consult, [data-fit-cta], a[href^="tel:"]')) return;
    var now = Date.now();
    if (now - lastCall < 3000) return;
    lastCall = now;
    window.NA_SEND('custom001');
  }, true);
})();

/* ===== itzip-head-6-crash.js ===== */
// 화면 죽음 감시. 큐샵(Next.js)이 본문 자리에
//     Application error: a client-side exception has occurred
// 를 띄우면, 그 사실과 직전에 난 자바스크립트 오류를 GA4 로 보냅니다.
//
// 왜 이게 필요한가: 2026-08-24 에 이 화면 스크린샷 한 장만 받았는데 어느 페이지인지,
// 무슨 오류인지, 브라우저가 무엇인지 아무것도 알 수 없었습니다. 콘솔을 볼 수 없는
// 사람이 보는 화면이라 본인에게 물어봐도 나오는 것이 없습니다. 그래서 다음에 또 나면
// 단서가 저절로 남게 합니다.
//
// 에러 화면의 실제 생김새는 이렇습니다. 헤더는 살아 있고 본문만 갈립니다.
//   #main
//    +- #headerSection            로고와 메뉴는 그대로 그려집니다
//    +- div style="height:100vh"  이 안에 위 문구
// 그래서 로고가 남아 있는 스크린샷도 이 오류가 맞습니다.
//
// 보내는 곳은 이미 깔려 있는 GA4(itzip-head-3-ga4.js) 입니다. 예약 웹훅을 쓰면 담당자
// 휴대폰으로 문자가 나가 버리므로 절대 그쪽으로 보내지 않습니다.
// GA4 실시간 화면에서는 app_crash 라는 이벤트 이름이 바로 보입니다. 안에 담은 값
// (page, errs, ua ...)까지 보고서에 띄우려면 GA4 관리 - 맞춤 정의에서 같은 이름으로
// 맞춤 측정기준을 한 번 만들어 주면 됩니다.
//
// 보고를 마친 뒤 한 번만 새로고침합니다. 가장 흔한 원인이 큐샵이 새 버전을 배포해서
// 열어 두었던 탭이 옛 조각(chunk)을 못 받는 경우인데, 그때는 새로고침 한 번으로
// 되살아납니다. 페이지 자체가 고장난 경우라면 다시 같은 화면이 나오지만 sessionStorage
// 표시 때문에 두 번은 안 돕니다. 무한 새로고침은 일어나지 않습니다.
// (같은 방식의 가드가 core-6-campaign-guard.js 에도 이미 있습니다.)
//
// 되돌리려면 이 조각 하나만 목록에서 빼고 다시 빌드하면 됩니다.
(function () {
  if (window.top !== window.self) return;   // 숨김 iframe 안에서는 세지 않습니다
  var MARK = 'Application error';
  var TAG = '[FIT CRASH]';
  var RELOAD = 1;                            // 0 으로 두면 보고만 하고 새로고침은 안 합니다
  var hits = [], logs = [], done = 0, timer = 0;

  function note(s) {
    s = String(s || '').slice(0, 200);
    if (!s || hits.length >= 5) return;
    for (var i = 0; i < hits.length; i++) if (hits[i] === s) return;   // 같은 오류 반복은 한 번만
    hits.push(s);
  }
  // 캡처 단계로 답니다. 리소스 로드 실패(스크립트, 이미지)는 버블링을 안 하기 때문입니다.
  window.addEventListener('error', function (e) {
    if (e.message) note('js ' + e.message + ' @' + String(e.filename || '').split('/').pop() + ':' + e.lineno);
    else if (e.target && (e.target.src || e.target.href)) note('load ' + (e.target.src || e.target.href));
  }, true);
  window.addEventListener('unhandledrejection', function (e) {
    var r = e.reason;
    note('rej ' + ((r && (r.message || r.name)) || r));
  });

  // 리액트는 화면을 갈아치우기 전에 오류를 자기가 삼킵니다. 그래서 위의 error 이벤트로는
  // 정작 원인이 안 올라옵니다. 실제로 2026-08-24 에 이 조각을 시험했을 때 오류를 일부러
  // 냈는데도 errs 가 비어 있었습니다. 대신 리액트는 그 오류를 console.error 로 반드시 한 번
  // 찍고 지나가므로 그쪽을 같이 엿봅니다.
  //
  // 마지막 세 줄만 굴려서 들고 있습니다. 큐샵도 평소에 console.error 를 쓰기 때문에, 전부
  // 모으면 정작 중요한 마지막 한 줄이 앞의 잡소리에 밀려납니다. 원본 console.error 는 그대로
  // 불러 주므로 개발자 도구에서 보이는 것은 달라지지 않습니다.
  try {
    var ce = console.error;
    console.error = function () {
      try {
        if (arguments[0] !== TAG) {
          var i, a, s;
          for (i = 0; i < arguments.length && i < 3; i++) {
            a = arguments[i];
            if (a && a.stack) s = String(a.message || a) + ' <- ' + String(a.stack).split('\n').slice(1, 3).join(' ');
            else if (typeof a === 'string') s = a;
            else continue;
            s = s.slice(0, 240);
            if (s.length > 8 && logs[logs.length - 1] !== s) { logs.push(s); if (logs.length > 3) logs.shift(); }
          }
        }
      } catch (e) {}
      return ce.apply(console, arguments);
    };
  } catch (e) {}

  // 에러 화면은 두 가지 모양으로 나옵니다. 2026-08-24 에 일부러 두 번 터뜨려서 둘 다 봤습니다.
  //   가) #main 과 #headerSection 은 살아남고 그 밑에 에러 상자만 들어옵니다.
  //       로고와 메뉴가 그대로 보입니다. 받았던 스크린샷이 이 모양이었습니다.
  //   나) #main 이 통째로 없어지고 #__next 바로 밑에 에러 상자 하나만 남습니다.
  //       완전한 백지입니다.
  // 그래서 #main 만 보면 나) 를 놓칩니다. 두 자리를 다 봅니다.
  //
  // 문구는 들어 있는지만 봅니다. 앞에서부터 맞추면 안 됩니다. 에러 상자 안에는 style 태그가
  // 먼저 들어 있어서 textContent 가 body{color:#000... 으로 시작하기 때문입니다.
  function inside(p) {
    if (!p) return 0;
    var k = p.children, i;
    for (i = 0; i < k.length; i++) {
      if (k[i].id === 'headerSection' || k[i].id === 'main') continue;
      if ((k[i].textContent || '').indexOf(MARK) >= 0) return 1;
    }
    return 0;
  }
  function dead() {
    // 제목도 같이 저 문구로 바뀝니다. 두 모양 모두에서 그랬고 한 번에 끝나는 검사라
    // 먼저 봅니다. DOM 검사는 큐샵이 제목을 되돌려 놓는 경우를 위한 보험입니다.
    if (String(document.title || '').indexOf(MARK) === 0) return 1;
    return inside(document.getElementById('__next')) || inside(document.getElementById('main'));
  }

  function report() {
    if (done) return;
    done = 1;
    if (timer) clearInterval(timer);
    var d = {
      page: (location.pathname + location.search).slice(0, 120),
      errs: hits.join(' | ') || '(window 오류 없음)',
      logs: logs.join(' | ') || '(console 오류 없음)',   // 리액트가 삼킨 진짜 원인은 보통 여기
      ua:   String(navigator.userAgent || '').slice(0, 160),
      size: (document.documentElement.clientWidth || 0) + 'x' + (window.innerHeight || 0),
      ref:  String(document.referrer || '').slice(0, 120)
    };
    try { console.error(TAG, d); } catch (e) {}   // TAG 로 보내야 위 엿보기가 자기 글을 안 줍습니다
    try { localStorage.setItem('fitCrash', JSON.stringify(d)); } catch (e) {}   // 그 사람 PC 를 볼 수 있을 때용
    try { if (window.gtag) window.gtag('event', 'app_crash', d); } catch (e) {}

    // 주소 끝에 ?fitdebug=1 을 붙이고 들어오면 화면에도 띄웁니다. 우리끼리 재현할 때
    // 콘솔을 열지 않고도 읽으려는 것입니다.
    if (location.search.indexOf('fitdebug') >= 0) {
      try {
        var b = document.createElement('pre');
        b.style.cssText = 'position:fixed;left:0;right:0;bottom:0;z-index:2147483000;margin:0;padding:12px;'
          + 'background:#121318;color:#ffce6a;font:12px/1.5 monospace;white-space:pre-wrap;max-height:50vh;overflow:auto';
        b.textContent = JSON.stringify(d, null, 2);
        document.body.appendChild(b);
      } catch (e) {}
      return;                                   // 디버그 중에는 새로고침하지 않습니다
    }

    if (!RELOAD) return;
    var key = 'fitCrashReload:' + location.pathname;
    try {
      if (sessionStorage.getItem(key)) return;  // 이 페이지는 이미 한 번 되살려 봤습니다
      sessionStorage.setItem(key, '1');
    } catch (e) { return; }                     // sessionStorage 가 막혀 있으면 절대 새로고침하지 않습니다
    // GA4 가 나갈 틈을 준 뒤에 다시 받습니다. 캐시를 지나치는 새로고침이라야 옛 조각을
    // 다시 잡지 않습니다.
    setTimeout(function () { location.reload(); }, 1200);
  }

  // setInterval 입니다. requestAnimationFrame 은 탭이 뒤에 있거나 창이 가려지면 아예
  // 안 불려서, 정작 오류가 난 화면을 못 볼 수 있습니다.
  timer = setInterval(function () { if (dead()) report(); }, 800);
  window.addEventListener('load', function () { if (dead()) report(); });
})();
